### ISSUE TITLE
0 Call to a member function getParams() on null

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#102]
Hi guys,
PHP 7.4.12 + Joomla 3.9.23 + Helix Ultimate alpha 2 +  SPPB 3.7.6:
- If I duplicate a SPPB page and/or I Export > Import a SPPB page
- When I'm going to open it in the Frontend (or Preview), I have back the error:

0 Call to a member function getParams() on null

All Permissions and Access pagel seem to be OK
As confirmed by Toufiq and tested, the bug is due to Helix Ultimate alpha 2 (on 1.1.2 is working right)

**Comment by ssnobben** [comment]
any solution?
