### ISSUE TITLE
Error "500 behavior::tabstate not found." when trying to edit the homepage 

### ISSUE THREAD

**Issue by Mohamed1308** [JoomShaper/helix-ultimate#103]
Hello.
I am currently using Joomla 4.0.0-beta5 with Helix Ultimate 2.0.0 Alpha 2 and PHP 7.3.

When I go to The Joomla administrator panel > SP Page Builder > Pages, I get the following error:
"An error has occurred.
500 behavior::tabstate not found."

Here is what I got in the logs file:
`CRITICAL .....	error	Uncaught Throwable of type InvalidArgumentException thrown with message "behavior::tabstate not found.". Stack trace: #0 ~/public_html/administrator/components/com_sppagebuilder/sppagebuilder.php(18): Joomla\CMS\HTML\HTMLHelper::_('jhtml.behavior....')`

Please inform me how to fix the above issue.

**Comment by ssnobben** [comment]
Have you tested Helix Ultimate 2.0.0 Alpha 3 and it still persist or is fixed?

**Comment by Mohamed1308** [comment]
Hello @ssnobben and thank you for replying.

I updated to Helix Ultimate 2.0.0 Alpha 3 and to Joomla! 4 Beta 6, but the problem still persists.

**Comment by Mohamed1308** [comment]
Here is how to reproduce the issue:
1) Download the Helix Ultimate Quickstart Package at https://www.joomshaper.com/downloads/template/helixultimate and upload it to your website's public_html folder.
2) Unzip the package file.
3) Go to www.yoursitename.com/installation/index.php and follow the installation procedures.
4) Upgrade **Helix Ultimate to 2.0.0 Alpha 3** (The download link: https://github.com/JoomShaper/helix-ultimate/releases/tag/v2.0.0-alpha.3) and **Joomla! to 4.0.0 Beta 6**.

I performed the above steps on a brand new website ( It uses **PHP 7.2** and **LiteSpeed server, NOT Apache**): I still got the same problem when clicking on SP Page Builder: "An error has occurred. 500 behavior::tabstate not found."

**Comment by Mohamed1308** [comment]
The above problem DOESN'T HAPPEN when following these steps:
1) Download Joomla! in your website and update it to version 4 Beta 6.
2) Download and install Helix Ultimate 2 Alpha 3 and set it as the default site template (https://github.com/JoomShaper/helix-ultimate/releases/tag/v2.0.0-alpha.3).
3) Download and install the free version of SP Page Builder (Lite version) (https://www.joomshaper.com/downloads/extension/sp-page-builder-free).
4) Import the database information of Helix Ultimate Quickstart Package to your website.
5) Change your website's configuration.php file to match the information of the imported database.
6) Update the SP Page Builder Database via the website's administrator control panel.

**Comment by Mohamed1308** [comment]
I found the above problem solved after using **Helix Ultimate 2 Beta 1 Quickstart Package**.
Thank you.
