### ISSUE TITLE
Error "500 icon::print_popup not found." when clicking on a blog article

### ISSUE THREAD

**Issue by Mohamed1308** [JoomShaper/helix-ultimate#104]
Hello.
I am currently using Joomla 4.0.0-beta5 with Helix Ultimate 2.0.0 Alpha 2 and PHP 7.3.

When I go to my website's homepage > Blog and then click on any article, I get the following error:
"500 icon::print_popup not found."

Here is what I got in the logs file:
`CRITICAL .......	error	Uncaught Throwable of type InvalidArgumentException thrown with message "icon::print_popup not found.". Stack trace: #0 ~/public_html/templates/shaper_helixultimate/html/com_content/article/default.php(160): Joomla\CMS\HTML\HTMLHelper::_('jhtml.icon.prin...', Object(stdClass), Object(Joomla\Registry\Registry))`

`CRITICAL ......	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page not found". Stack trace: #0 ~/public_html/libraries/src/Application/CMSApplication.php(1008): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)`

Please inform me how to fix the above issue.

**Comment by ahamed** [comment]
Hello @Mohamed1308 
Could you please tell me how to recreate the issue? Is there anything have you done for getting the issue?

**Comment by Mohamed1308** [comment]
Hello @ahamed. Here are the steps to reproduce the above issue:

1. Download Joomla! in your website and update it to version 4 Beta 7.
2. Download and install Helix Ultimate 2 Alpha 5 and set it as the default site template.
3. Download and install the free version of SP Page Builder (Lite version).
4. Import the database information of Helix Ultimate Quickstart Package to your website.
5. Change your website's configuration.php file to match the information of the imported database.
6. Update the SP Page Builder Database via the website's administrator control panel.

**Comment by Mohamed1308** [comment]
@ahamed  Please notice that the problem still persists with **Joomla 4 Beta 7** and **Helix Ultimate 2 Alpha 5**.

Here is a corrected version of the step-by-step instructions to reproduce the issue:
1. Download Joomla! in your website AND update it to version 4 Beta 7.
2. Download Helix Ultimate 2 Alpha 5, install it in your website and set it as the default site template.
3. Download and install the free version of SP Page Builder (Lite version).
4. Import the database information of Helix Ultimate Quickstart Package to your website:
    a. Create a second website using the quickstart package: https://www.joomshaper.com/downloads/template/helixultimate.
    b. Update it to Joomla 4 Beta 7 and Helix Ultimate 2 Alpha 5.
    c. Download the second website's Joomla databse (let's call it sampleDB.sql).
    d. Create a new database in your FIRST website and import sampleDB.sql to it.
5. Change your website's configuration.php file to match the information of sampleDB.sql.
6. Update the SP Page Builder Database via the website's administrator control panel.
7. Go to your website's Homepage > Blog and then click on any article.
Here is an example: freepetsitters.com/blog/how-marching-for-science-risks-politicizing-it.

I also made some changes to freepetsitters.com prior to the 7 steps above, but the problem appeared immediately after performing them.

**Comment by Mohamed1308** [comment]
Hello @ahamed. Please notice that the problem still persists with **Joomla 4 Beta 7** and **Helix Ultimate 2 Beta 1**.

Here is how I got the "500 error" issue this time:
1. I recreated a website from scratch by using the Helix Ultimate 2 Beta 1 Quickstart Package. The website is: https://www.freepetsitters.com.
2. I upgraded the website to Joomla 4 Beta 7.
3. When I go to my website's Homepage > Blog > Click on any blog article, I get the error: **500 icon::print_popup not found**.

**Comment by Mohamed1308** [comment]
The above problem still persists with **Helix Ultimate 2 Beta 2** and **Joomla 4 Beta 7**.

**Comment by Mohamed1308** [comment]
Same issue with Helix Ultimate 2 **Beta 3** and Joomla 4 Beta 7.

**Comment by mdamjadrana** [comment]
I tested everything perfectly. Saw everything works fine. Maybe something wrong with your settings.

**Comment by Mohamed1308** [comment]
@mdamjadrana I still get the same problem when using Joomla 4 RC 1 and Helix Ultimate 2 Beta 3.

**Comment by Mohamed1308** [comment]
@mdamjadrana @ahamed Same problem with Helix Ultimate 2 RC1 and Joomla 4 RC2.

**Comment by mdamjadrana** [comment]
Solved, try with this.
[2.0.0-rc.2.zip](https://github.com/JoomShaper/helix-ultimate/files/6693075/2.0.0-rc.2.zip)

**Comment by mdamjadrana** [comment]
Solved.
