### ISSUE TITLE
Cannot access protected property Joomla\CMS\Menu\MenuItem::$params" in ~/public_html/modules/mod_menu/mod_menu.php(27): require()

### ISSUE THREAD

**Issue by Mohamed1308** [JoomShaper/helix-ultimate#107]
Hello.
I am currently using Joomla 4 Beta 6 with Helix Ultimate 2 Alpha 3 and PHP 7.2. on a LiteSpeed-based server.

When I go to my website's homepage, I get the following error:
**"Error: 0 Cannot access protected property Joomla\CMS\Menu\MenuItem::$params"**

Here is what I got in the logs file:

_Uncaught Throwable of type Error thrown with message "Cannot access protected property Joomla\CMS\Menu\MenuItem::$params". Stack trace: #0 ~/public_html/modules/mod_menu/mod_menu.php(27): require()_

The 27th line of the mod_menu.php file is:
`require ModuleHelper::getLayoutPath('mod_menu', $params->get('layout', 'default'));`

Please inform me how to fix the above issue.

**Comment by ghazal** [comment]
hello,
same error in Joomla 4 Beta 7 with Helix Ultimate Alpha 4 and PHP 8.0

**Comment by ahamed** [comment]
Hello @ghazal,
Did you check `2.0.0-alpha.5`? Your issue has been fixed there. If it is then please let us know.
Thanks.
