### ISSUE TITLE
Section ID

### ISSUE THREAD

**Issue by GerritArt** [JoomShaper/helix-ultimate#110]
Trying to work with Section ID's. Problem occurred when adding a name in Section ID i.e. 1vision.
The styling (color, margins) was in front end mode still visible but after saving and closing edit page, the styling disappeared.
working with joomla 3.9.24 | helix ultimate vs 2.0.0-alpha.3.

**Comment by ahamed** [comment]
Could you please elaborate on your problem? Please tell us how to recreate the situation step by step.
Thanks.

**Comment by GerritArt** [comment]
Hi,
I got this advice to tell Github after contacting support from Joomshaper. Because I use Joomshaper pagebuilder icm Helix Ultimate. <br>
The Steps:
Login via Front end -->Edit Page --> Selecting Row-options for Section --> Container Style Settings --> Section ID --> i.e 1vision. Goal is to create an anchor link. <br>
Section style I choose to color red and margins 125px from top and bottom. In the preview screen I can see the good results. After saving and loading the page without editor open, all those settings are not shown. The anchor link works but styling not.

**Comment by ahamed** [comment]
Is the problem introduced at `v2.0.0-alpha.x`, or you got it before with `v1.x`?

**Comment by GerritArt** [comment]
This is the first time I tried such a thing.

Kind regards,
Gart van der Pol


Op 3 feb. 2021 om 16:53 heeft Sajeeb Ahamed <notifications@github.com> het volgende geschreven:

﻿

Could you please elaborate on your problem? Please tell us how to recreate the situation step by step.
Thanks.

**Comment by Pawel-Support** [comment]
Are you sure that you talk about Helix Ultimate, not SP Page Builder? Those are two different products.  @GerritArt GerritArt

**Comment by mdamjadrana** [comment]
I saw that in the helix layout builder section settings working fine.
If you face any problem-related sp page builder then please post in the JoomShaper forum.
