### ISSUE TITLE
Header and Offcanvas BUGs

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#111]
Hi guys,
PHP 7.4.14 + Joomla 3.9.24 + Helix Ultimate 2.0 Alpha 4

1 - the Header logo image / modules are doubled - you can see [in action here](https://test2.egulp.net/)

2 - the Offcanvas is appended below the Header causing an obliuous movement on open / close

3 - the Header is added on top of the page without moving down the page with the result that the body content is glued directly on the header

I suppose the 3 things are related, this is why I posted them together

**Comment by ahamed** [comment]
Hello @joomleb,
Thanks for creating issues and helping us to improve the framework. Could you please clarify on-

+ What do you mean by **Header logo image/modules are doubled**? The video link have you shared is not available.
+ "The Offcanvas is appended below" - is it at the template editing or template frontend? If you are talking about this 
![image](https://user-images.githubusercontent.com/5783354/107109528-7645b000-686b-11eb-8ff5-e36e70f7b0bd.png)
then it is completely okay.
+ For the third problem could you please add a screencast or at least a screenshot?

**Comment by joomleb** [comment]
Hi @ahamed 
man thanks to you for Support. So:

1 - "Doubled" - The link I provided you is not to a video, but to the Test2 site where the Alpha 4 is installed. You can compare it with the [live site](https://507panama.com/) where Helix Ultimate 1.1.2 is running without the issue
As you can see the Logo (on the left) and the language Module switcher (on the right), both into the Header, are Doubled, shown two times.

2 - "Offcanvas" - Open and Close the Offcanvas menu on frontend on both sites and you will see

3 - Always comparing the two sites, take a look where the body is appended below the header and you will see it

**Comment by ahamed** [comment]
Sorry, I thought you had shared a video 😉 
Now I get the "Doubled" issue. As it is not showing on my end, I have to inspect your site a little bit. Could you please share your administrator access via email `sajeeb07ahamed@gmail.com`?

For the "Offcanvas" issue, I've changed the Offcanvas transition style.

And the third issue I think related to the first issue.

**Note: Did you install `v2.0.0-alpha.4` on top of `v1.1.2`?**

**Comment by joomleb** [comment]
Hi @ahamed 
I sent to you by email the Super Admin access to Test2 site...

"Note: Did you install v2.0.0-alpha.4 on top of v1.1.2?" - Maybe

PS - On mobile the Offcanvas is not opening, clicking on the icon nothing happen

**Comment by joomleb** [comment]
@ahamed 
as far as I see you worked on it and you uninstalled > reinstalled HU. I played around and:

1 - "Doubled" - It seems has been solved

2A - "Offcanvas" - Open and Close movement > you added a not it will be fixed on next release
2B - Anyway, be careful, on mobile if I click on the Offcanvas menu icon, nothing happen...

3A - "Logo" - to solve it I have to select the "Retina Logo" image that, when selected, it doesn't follow the Logo height setting.
3B - "Body is appended below the header " - It seems like the "Main Body Row Options > Style > Padding: 20px 15px 20px 15px" setting is not applied

**Comment by joomleb** [comment]
@ahamed
tested Alpha 5, NOT solved:

2A - "Offcanvas" - Open and Close movement
Opening Left Offcanvas the Body is moved on the right, while Offcanvas should slide over the entire site (Header and Body)

3A - "Logo"
when the "Retina Logo" image is selected the image is shown smaller than the 2 pixels height setting (on 1366x768 screen) while a "resizing" is not applied on mobile and it should...

The Logo image (img and a) is shown as 300 pixels width, while it should be 225.33 (with 32 pixels I set), the result is that the image is wasting space and it seems like centered instead of left aligned

3B - "Body is appended below the header " - Still, It seems like the "Layout Builder > Main Body Row Options > Style > Padding: 20px 15px 20px 15px" setting is not applied. This because is like the sp-main-body section is not appended below the header but below it...

**Comment by joomleb** [comment]
@ahamed with
tested Alpha 6, NOT solved and:

4 - the fa fa-bars Offcanvas icon has disappeared...

**Comment by ahamed** [comment]
I've installed `2.0.0-alpha.6` in your [test2](https://test2.egulp.net) site. I saw the Offcanvas is working correctly.
Here I attach an image how "Offcanvas" looks like now-


![image](https://user-images.githubusercontent.com/5783354/109279129-943b7a80-7843-11eb-8f50-f751d3256c02.png)

**Comment by joomleb** [comment]
@ahamed 
Are you sure ?
it is not working as your image on my Chrome browser, "it is all corrupted"
maybe, Have you done others changes / works ?
Am I missing anything ?

**Comment by ahamed** [comment]
@joomleb, yes this is your browser cache, the villain. For getting the offcanvas (the image I've shared the previous comment) I have to just install the alpha 6 version. And for double header issue from the layout builder I've change the first row. Please use predefine header instead such a way.

**Comment by joomleb** [comment]
@ahamed 
I hope to be able to work soon on testing it without using the "predefined header", I'm really not liking where is going Helix Ultimate. It seems are going to be more complicated just to have fixed things, instead to be an "Open" template framework.

Anyway, there are still 2 things that are not running with the predefined header:
1 - The Title Row > Style > Padding: 0px 15px 0px 15px setting is not considered and is not applied
2 - My SCLoging module assigned to the offcanvas position is not shown into the offcanvas 
3 - Can you assign 1rem to the Offcanvas menu items dimensions without any special spacing ? By deafult right now are really too big and too spaced and the offcanvas menu is wasting a lot of height space
