### ISSUE TITLE
[2.0.0 alpha 5] Update en-GB.tpl_shaper_helixultimate.ini

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#112]
I found some mistakes in language file.

123 HELIX_ULTIMATE_MINUTE="Mimnute" (update to "Minute")
144 HELIX_ULTIMATE_SOCIAL_ICON_WHATSAPP="Whtasapp Username" (update to "Whatsapp Username")

**Comment by ahamed** [comment]
Thank you @Bond97. This must be fixed at `alpha.5`.

**Comment by ahamed** [comment]
Hello @Bond97,
Did you check that the `2.0.0-alpha.5` fixes your issue? If so, then let us know, we can close the issue.
