### ISSUE TITLE
Notice: Trying to access array offset on value of type null in Compiler.php on line 3624

### ISSUE THREAD

**Issue by alebak** [JoomShaper/helix-ultimate#113]
https://github.com/JoomShaper/helix-ultimate/blob/15693ada65b93c4c75844fd4d70d512e2fc6f916/plugins/system/helixultimate/core/classes/scss/Compiler.php#L3624

This notice is displayed since Helix Ultimate v1.x version:

Notice: Trying to access array offset on value of type null in D:\laragon\www\joomla4\plugins\system\helixultimate\src\core\classes\scss\Compiler.php on line 3624

My System Information:

|                    Setting                     |                                                        Value                                                        |
|------------------------------------------------|---------------------------------------------------------------------------------------------------------------------|
|                  PHP Built On                  |                                Windows NT SIRIUS 10.0 build 19042 (Windows 10) AMD64                                |
|                 Database Type                  |                                                        mysql                                                        |
|                Database Version                |                                                       5.7.24                                                        |
|               Database Collation               |                                                  latin1_swedish_ci                                                  |
|         Database Connection Collation          |                                                 utf8mb4_general_ci                                                  |
|         Database Connection Encryption         |                                                        None                                                         |
| Database Server Supports Connection Encryption |                                                         No                                                          |
|                  PHP Version                   |                                                       7.4.10                                                        |
|                   Web Server                   |                                   Apache/2.4.35 (Win64) OpenSSL/1.1.1g PHP/7.4.10                                   |
|           WebServer to PHP Interface           |                                                   apache2handler                                                    |
|                Joomla! Version                 |                            Joomla! 4.0.0-beta7 Beta [ Mañana ] 2-February-2021 19:23 GMT                            |
|                   User Agent                   | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 |

**Comment by ahamed** [comment]
Hello @alebak, we hope alpha.6 has fixed your issue. Did you check it? If it is fixed then let us know and close the issue.
Thanks.

**Comment by alebak** [comment]
Checked!
