### ISSUE TITLE
[2.0.0-alpha.6]Php error when enable "Fullwidth Left" predefined header

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#114]
Hello! I've been testing new alpha6 release on my test domains (Joomla 4 beta 7 and Joomla 3.10.0-alpha5).

When I select "Fullwidth Left" predefined header in template menu and save it, I saw this error "syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)". It has been on both Joomla versions.

There is no errors, if I select any other predefined headers. I attach screenshot with error.

![изображение](https://user-images.githubusercontent.com/78050514/108912230-684ca900-7639-11eb-9f9d-c462d5af963a.png)

**Comment by ahamed** [comment]
Thank you @Bond97 for your response. We've provided a hotfix for your issue in the same alpha version. Please download the package once again and install it on top of your previous installation.

For your information, you can download it from https://github.com/JoomShaper/helix-ultimate/releases/tag/v2.0.0-alpha.6

**Comment by Bond97** [comment]
It has been fixed, I reinstall template from updated file. Thank you!
