### ISSUE TITLE
Bug helix ultimate + SP Pagebuilder php 8 ?

### ISSUE THREAD

**Issue by ssnobben** [JoomShaper/helix-ultimate#115]
Hi have you tested Helix Ultimate with SP Pagebuilder with php 8 and Joomla 4 too? are they working now?

these are old errors coming from php 8.0.1 and SP Pagebuilder for example

Call   stack
--
# | Function | Location
1 | () | JROOT/components/com_sppagebuilder/helpers/css-parser.php:143
2 | include() | JROOT/libraries/src/Layout/FileLayout.php:125
3 | Joomla\CMS\Layout\FileLayout->render() | JROOT/components/com_sppagebuilder/parser/addon-parser.php:472
4 | AddonParser::getAddonHtmlView() | JROOT/components/com_sppagebuilder/parser/addon-parser.php:292
5 | AddonParser::viewAddons() | JROOT/templates/shaper_helixultimate/html/com_sppagebuilder/page/default.php:95
6 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:701
7 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:230
8 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/components/com_sppagebuilder/views/page/view.html.php:43
9 | SppagebuilderViewPage->display() | JROOT/libraries/src/Cache/Controller/ViewController.php:102
10 | Joomla\CMS\Cache\Controller\ViewController->get() | JROOT/libraries/src/MVC/Controller/BaseController.php:663
11 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_sppagebuilder/controller.php:68
12 | SppagebuilderController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:710
13 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_sppagebuilder/sppagebuilder.php:20
14 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
15 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
16 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:194
17 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:233
18 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:196
19 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49

**Comment by ahamed** [comment]
Thank you for your response. Wait for at least beta.1. We will make it compatible with php8.

**Comment by ahamed** [comment]
Hello @ssnobben,
The issue belongs to the SP Page Builder + PHP 8. Our team working on __SP Page Builder__ for making compatible it of __PHP 8__. I wish after the next update of Page Builder the issue will be gone.

Thanks.

**Comment by ssnobben** [comment]
Hi Ahamed thanks for update. Cheers!
