### ISSUE TITLE
[2.0.0-alpha.7] Error "Expired" when select single article as home page

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#117]
Hello! I have testing latest alpha release and find this error.

![изображение](https://user-images.githubusercontent.com/78050514/109954651-a3627280-7cf2-11eb-8a84-b7ceaa33f672.png)

**Steps to reproduce error:**
1. Create new article without any content. Simply click "create", write title "test" and click "save and close"
2. Go to "menus" component
3. Select at home page menu item this parameters: "single article" and article "test". Click "save and close"
4. Go to home page http://domain.tld
5. You will see this error, that I attached above

**Note:** if you select "featured articles" in homepage menu item, this error is gone. Screenshot attached below.

![изображение](https://user-images.githubusercontent.com/78050514/109957709-6304f380-7cf6-11eb-9b1a-caef5119507d.png)

This error is showing, when selected "single article" or "category blog".
In web browser console I see, that error write in css class "article header". But I write nothing in that parameter.

```
<div class="article-body">
<div class="system-unpublished">
<div class="article-header">
<span class="badge badge-warning">Expired</span>
</div>
```

Is this a bug in helix template or I must create issue on joomla cms repo?

When I select as main template "cassiopeia", there is no errors like that.

PHP 7.4.15, MySQL 5.7.23-cll-lve, Joomla 4.0.0 beta 7.

**Comment by ahamed** [comment]
I've followed your instruction-
- Go to `Content > Articles`
- Click the `New` button
- Put **Test** on the title field.
- Click `Save & Close` button.
- Go to `Menus > Main Menu`
- In the **Home** menu I select `Single Article` and select the `Test` article.
- Go to site and no problem found there.

![image](https://user-images.githubusercontent.com/5783354/109959476-bdf81400-7d11-11eb-9724-7d1b994a9da4.png)

**Comment by Bond97** [comment]
Hmm, strange.. Could you re-test it at latest nightly joomla build (beta 8 dev)?
I have re-test: reinstall blank template and error is showing again.

![изображение](https://user-images.githubusercontent.com/78050514/109962915-d7db2c00-7cfc-11eb-9f06-5b9272293787.png)

Or must I test your "quickstart" environment?

**Comment by Bond97** [comment]
@ahamed I have tested in cloudaccess.net (launch.joomla.org)

Select (joomla 4.0.0 dev 8), install latest alpha version of helix template and do this steps above.

If you have opportunity, could you re-test it on cloudaccess hosting?

My testing Joomla 4 is in another hosting, I make new environment on cloudaccess.

**Comment by ahamed** [comment]
Hello @Bond97,

I've found the issue. The issue belongs to the Joomla! 4. Currently the Joomla! 4 not in its stable stage. Thanks once again.

**Comment by ahamed** [comment]
@Bond97 
Could you please check at `beta.2` that the issue is fixed or still persisted?
Thanks.

**Comment by Bond97** [comment]
@ahamed I've test it on my second test site - it has been fixed. First test site I will be rebuild completely and I hope, that error has gone.
![изображение](https://user-images.githubusercontent.com/78050514/114376004-ecc59d80-9b8d-11eb-90ef-b6202da0ae8b.png)

Thank you!
