### ISSUE TITLE
[2.0.0-alpha.7] Off-canvas badge is showing twice

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#118]
**Steps to reproduce error:**
1. Go to template settings (system->site template settings->shaper_helixultimate)
2. Set predefined header as "Large header"
3. Turn on "mobile view"
4. Off-canvas badge is showing twice

![изображение](https://user-images.githubusercontent.com/78050514/109964037-30f78f80-7cfe-11eb-87e6-29fcb04af845.png)

Environment same as #117 

Note: that problem has showing when select "tablet view" too.

**Comment by ahamed** [comment]
Hello @Bond97,
I've tested the last version with `Joomla-beta8-dev` and no issue found.

![image](https://user-images.githubusercontent.com/5783354/110080427-a1f97e80-7db4-11eb-9d74-c2fcfa2ddb35.png)

**Comment by Bond97** [comment]
@ahamed I find solution to hide twice badge- select `mega menu + off-canvas` or `off-canvas` in menu settings.

![изображение](https://user-images.githubusercontent.com/78050514/110167596-05140100-7e07-11eb-8a5b-da22402f1b2a.png)

Twice badge is appearing when I select `mega menu` in that frame.

But when I select `mega menu+offcanvas` it will be show unnecessary off-canvas badge in desktop view.

![изображение](https://user-images.githubusercontent.com/78050514/110167546-f3caf480-7e06-11eb-82c5-bb0ae03b5229.png)

Could you re-test it on your environment? For example latest Joomla 4.0.0 beta8-dev

**Comment by ahamed** [comment]
Hello @Bond97,
The issue has been detected. We will fix this in the next version. Thank you for your effort.

**Comment by Bond97** [comment]
Issue has been fixed on beta 1 release, thanks!
