### ISSUE TITLE
[joomla 4][PHP8][v.2.0.0-alpha.7] Error on com-tags

### ISSUE THREAD

**Issue by ghazal** [JoomShaper/helix-ultimate#119]
This is an issue related to J4.
I have not tested the solution I suggest on a 3.9.xx version - that's why i didn't do a PR.

When clicking on a tag I got a "Class TagsHelperRoute not found".
Actually naming of the class has been changed.
My solution:
Add  ``use Joomla\Component\Tags\Site\Helper\RouteHelper;`` on top of the relevant files.
In: ``<?php echo Route::_(TagsHelperRoute::getItemRoute ...``
replace ``TagsHelperRoute ``
by ``RouteHelper ``

Wherever necessary.

BTW, I replaced
 `` HTMLHelper::addIncludePath(JPATH_COMPONENT . '/helpers'); ``
``HTMLHelper::_('behavior.core'); ``

by:
`` /** @var Joomla\CMS\WebAsset\WebAssetManager $wa */``
``$wa = $this->document->getWebAssetManager();``
``$wa->useScript('com_tags.tag-default'); ``

As shown in the original J4 files for com_tags.

**Comment by ahamed** [comment]
Hello @ghazal,
Thank you for your efforts. You can create `Pull Request` and we highly appreciate your tries. Here in `Helix Ultimate v2.0.0` we are going to provide both Joomla! 3 & 4 support by the same package.

So if you have to introduce something which is not in Joomla! 3 but new in Joomla! 4 then you have to put both codes for J3 & J4. For that, you can check the Joomla! version first like-

```php
if (JVERSION < 3)
{
    // Write the codes for Joomla! 3
}
else
{
    // Write the codes for Joomla! 4
}
```

Note: For making PR - 
- Fork the repository.
- Create a branch from the **master** branch (Important)
- Write your codes and changes.
- Make a pull request
