### ISSUE TITLE
logo is showing up twice

### ISSUE THREAD

**Issue by n00bster** [JoomShaper/helix-ultimate#120]
hi,
two logos are displayed next to each other. i have had this problem since the first test installation of the alpha version.
in the seventh version the problem still exists, so i want to point it out.
I have already cleared the cache, but the problem remains.
![05-03-_2021_15-37-46](https://user-images.githubusercontent.com/1003469/110131467-741f3480-7dca-11eb-9d87-5144d12356ce.jpg)

**Comment by Bond97** [comment]
I have that problem too, it has solved by completely reinstall joomla.

**Comment by n00bster** [comment]
> I have that problem too, it has solved by completely reinstall joomla.
hi Bond97, that is not a option for my existing project :)
for the dev's: what i also noticed, if i deactivate the "lazy load for images" the problem is gone.

**Comment by ahamed** [comment]
Hello @n00bster,
I've fixed your issue. The problem lies in the **Image Lazy Loading** functionalities. For checking the changes go to
https://github.com/JoomShaper/helix-ultimate/tree/2.0.0-beta.1
and follow the steps wrote in the readme file.
