### ISSUE TITLE
Not possible to hide menu title

### ISSUE THREAD

**Issue by vandersell** [JoomShaper/helix-ultimate#121]
I want to show menu item with icon and without menu title.

Showing an icon is easy
`HU2.0.0  > Menu > Menu Builder > Mega Menu > Icon`
The icon will be displayed to the left of the menu item text, as expected.

To hide Menu Title from menu
`Joomla3 > Edit Menu Item > Link Type > Add Menu Title > No`
Expected result: menu title will be hidden
**Actual result**: menu title is still visible

HelixUltimate1 had MegaMenu option 'Show Menu Title', but it is no longer in HU2.0.0

PS.
I also can't figure out how to remove the icon?
HelixUltimate1 docs: "To remove the icon, select the “Select” name, then save settings."
There is no 'Select' in dropdown in HU2.0.0

**Comment by ahamed** [comment]
Hello @vandersell,
Thank you for mentioning an important issue. The `Show Menu Title` is also existing in `HU2.0.0` but the problem appears if you enable the mega menu settings. This must be fixed at `beta1`.

For clearing the menu icon an option has already been added. You will get the reflection of this at `beta1` as well.

**Comment by ahamed** [comment]
Hello @vandersell,
I believe your issue has been fixed at the `2.0.0-beta.1` version. Please check it out.

**Comment by vandersell** [comment]
Hiding and showing menu item title and icon works `HU2.0.0-beta.1` as expected.
Thank You!
