### ISSUE TITLE
[2.0.0-beta.1] Phone and email badges are non properly rendered in "Full modal" mode

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#122]
I've been testing new beta.1 release on latest `Joomla 4.0.0-beta8-dev`.

**Steps to reproduce issue:**

1. Go to `System-> Site template styles-> shaper_helixultimate - Default`
2. Enable `Contact Info` on following menu.
3. Select in Header menu `Full Modal` mode
4. Click on `off-canvas` badge
5. Phone and email badges are not rendered in one line.

Screenshot attached below.

![изображение](https://user-images.githubusercontent.com/78050514/111831086-ed0ca900-88ff-11eb-8981-9b5e93de9ce5.png)

Is that a bug or it's a new feature?

Additional details: Firefox 87.0, Joomla 4.0.0-beta8-dev, php 7.4.0

**Comment by ahamed** [comment]
Hello @Bond97 
This issue is fixed at `2.0.0-beta.2`. Could you please confirm that the issue is fixed?

**Comment by Bond97** [comment]
@ahamed Hmm, are you decided to completely remove this badges? I didn't see it :)

![изображение](https://user-images.githubusercontent.com/78050514/114365695-5ee4b500-9b83-11eb-9f85-ebab79453a56.png)

If it will be your fix-that's ok, I will close issue. If not- please add back that badges in one line with email and phone text.

**Comment by ahamed** [comment]
Did you check that the `Social Icons` and `Contact Info` are enabled?
If not then please enable them.

**Comment by Bond97** [comment]
@ahamed I've just check it on my another test site on same environment - it has been fixed correctly

![изображение](https://user-images.githubusercontent.com/78050514/114375030-f13d8680-9b8c-11eb-81cb-2de36489efac.png)

Thank you!
