### ISSUE TITLE
Install Error (J4.beta7 - helix 2 alpha 2

### ISSUE THREAD

**Issue by alfredojdd** [JoomShaper/helix-ultimate#131]
Hi, excuse my english.
When I try to install the template I get the following error and the installation stops
![helix01](https://user-images.githubusercontent.com/17855375/112825836-8704ec00-908c-11eb-9f8d-c390b51b7c9e.PNG)

**Comment by ahamed** [comment]
Hello @alfredojdd,

Were the plugin and template installed? I've just installed it on `Joomla v4.0.0-beta.7` and no problem found. Could you please share your system information with us?

Thanks.

**Comment by alfredojdd** [comment]
Sure. Here you have
[systeminfo-2021-03-29T11_22_36+00_00.txt](https://github.com/JoomShaper/helix-ultimate/files/6221342/systeminfo-2021-03-29T11_22_36%2B00_00.txt)

**Comment by ahamed** [comment]
Which Helix Ultimate version you are trying to install?

**Comment by alfredojdd** [comment]
This:
https://github.com/JoomShaper/helix-ultimate/releases/download/v2.0.0-alpha.2/2.0.0-alpha.2.zip

**Comment by ahamed** [comment]
`v2.0.0-alpha.2` is a very old version. The latest one is `v2.0.0-beta.1`. Please download it from here https://github.com/JoomShaper/helix-ultimate/releases/download/v2.0.0-beta.1/2.0.0-beta.1.zip and install it.

**Comment by alfredojdd** [comment]
Thanks for your advice.
With the beta.1 file..same error:
![helix02](https://user-images.githubusercontent.com/17855375/112947486-25e62280-9137-11eb-860e-a0e1d4505825.PNG)

**Comment by ahamed** [comment]
This is really weird. No one encountered this problem before. Are the Helix Ultimate plugin and template installed or not? Could you please try installing Joomla 4 once again and install the `Helix Ultimate 2.0.0-beta.1` again.

**Comment by alfredojdd** [comment]
No installed. None of both
Will try with a fresh install....

**Comment by alfredojdd** [comment]
Good news.
With a fresh install everything worked correctly.
Thanks.

**Comment by ahamed** [comment]
Thanks for mentioning.
