### ISSUE TITLE
Problem with mega menu in multi-language 

### ISSUE THREAD

**Issue by nadird** [JoomShaper/helix-ultimate#135]
Hi, i'm testing helix ultimate since alpha 2 there is a problem with multilingual main menu, 
the main menu apears in the main language but doesn't apear in the other languages. 

you can see it here : https://evact.fr/ (it's not in production mode)

**Comment by ahamed** [comment]
How to recreate the issue? Did you configure the multilingual correctly?

**Comment by nadird** [comment]
yes it's the same config of my production website that works on helix3 https://www.evact.net/  
i've juste cloned the production website in https://evact.fr/ i can provide access if you want to see

**Comment by ahamed** [comment]
Please give me access. My email address is `sajeeb07ahamed@gmail.com`

**Comment by nadird** [comment]
I just sent

**Comment by ahamed** [comment]
Hello @nadird,
I've fixed the issue for you and the solution will be shipped with the `2.0.0-beta.2`.
Thanks for finding the issue.

**Comment by nadird** [comment]
My pleasure @ahamed
