### ISSUE TITLE
Helix Ultimate 2.0.0-beta.1 no mega menu render desktop on multilanguage site second language

### ISSUE THREAD

**Issue by ssnobben** [JoomShaper/helix-ultimate#137]
Hi 

when have a multilangauge site the desktop mega menu doesnt render at all and not show up on the second language no mega menu shows up but the off canvas show up but also not render any of the second language menus items there only show the search there but no menus. 

So there is some desktop mega menu issues with this non english std menu ( top bar heading ) setting. 
![NoMenu](https://user-images.githubusercontent.com/6490832/113502674-0df31200-952e-11eb-94eb-85d9541db8bc.jpg)

**Comment by ahamed** [comment]
The same issue has been opened by another person in #135 and we fix it at the next version `2.0.0-beta.2`.
