### ISSUE TITLE
Suggestion (beta2): Option Description

### ISSUE THREAD

**Issue by Pawel-Support** [JoomShaper/helix-ultimate#139]
Now is:
You can enable/disable the fontawesome icons to load your site

I think much more correct would be:
You can enable/disable the Font Awesome 5 icons to load on your site

**Comment by ahamed** [comment]
I don't understand your point.

**Comment by Pawel-Support** [comment]
1) fontawesome - is not fully correct spelling name of this product. 
2) by adding "5" people would know what version they use.

**Comment by ahamed** [comment]
We can change the `fontawesome` to `Font Awesome`. But there no need of using the version number. We should use the generic name.

**Comment by Pawel-Support** [comment]
No problem, I will add this info in Helix documentation after all. 
Just rename.
