### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by komir2004** [JoomShaper/helix-ultimate#140]
Hi, in the last version 2.0 beta2 mobile menu icon is not visible

**Comment by ahamed** [comment]
Hello @komir2004,
Thank you for your issue. Please write us a little more about how to recreate the issue and specifically where do you get the problem.

**Comment by ahamed** [comment]
Please select an Offcanvas style.  For selecting go to - 
`Menu > Off-canvas` then select a style.

![image](https://user-images.githubusercontent.com/5783354/114223032-27aeb200-9991-11eb-89aa-d8e211435142.png)

**Comment by komir2004** [comment]
I did like you say (selected Center Algin) but nothing is changed

**Comment by ahamed** [comment]
Could you give me your administrator access via email? `sajeeb07ahamed@gmail.com`

**Comment by ahamed** [comment]
After inspecting your settings carefully I've found that you've used some custom CSS inside the `Custom Code > Custom CSS` setting. This is the culprit for your problem. If you remove the CSS then everything will be okay.

<img src="https://user-images.githubusercontent.com/5783354/114229870-39488780-999a-11eb-868c-acfa47d278e4.png" width="400" />

**Comment by komir2004** [comment]
Thank you, now it is ok

**Comment by komir2004** [comment]
Please can you take a look at https://www.matica-uik.hr/ this also a mobile menu problem. 
When clicking on the mobile menu (burger) nothing is happening.
Tnx

**Comment by komir2004** [comment]
Solved. Compress Javascript files was enabled inside tempate
