### ISSUE TITLE
breadcrumbs are different // beta 2

### ISSUE THREAD

**Issue by n00bster** [JoomShaper/helix-ultimate#141]
hi.
with the beta 1 version the breadcrumbs in the bottom looks like this:  
https://www.screencast.com/t/hyzoD1xlUY

and in the beta 2 version it is different, also the page width was further increased with the update: https://www.screencast.com/t/6Vz9CEJdUwsw

looks like some css styles gone missing from beta 1 to beta 2.

Joomla! Version | Joomla! 3.9.25
PHP Version | 7.4.16

**Comment by ahamed** [comment]
Is it for Joomla3 or Joomla4?

**Comment by n00bster** [comment]
sorry, at joomla 3

**Comment by ahamed** [comment]
There is no problem with installing beta2 over beta1. BTW, if you want to keep your settings then export the settings from beta1 then install beta2 and import the settings file.

**Comment by n00bster** [comment]
I understand, thank you. I have saved the config and uninstalled and reinstalled the beta 2 and it is the same behavior.
also i noticed the error about bootstrap in the browser console:
https://www.screencast.com/t/WcZ9ZziS

**Comment by Pawel-Support** [comment]
@n00bster 
It's when Boostrap trying to load file that doesn't exist, it will be fixed. 
But you can now as well, just edit  css\bootstrap.min.css
and remove the comment line at the bottom:

`/*# sourceMappingURL=bootstrap.min.css.map */`
