### ISSUE TITLE
BUG: Beta2 and  custom.css file

### ISSUE THREAD

**Issue by Pawel-Support** [JoomShaper/helix-ultimate#144]
When I add a custom.css file to the template's css folder it doesn't seem to recognize it, where as it did with the previous beta1.
It was noticed in the comments under the blog post, but I put it also here to not forget.

I hope The issue will be fixed in the next, RC version.

**Comment by gourou69** [comment]
create a "custom" folder in "css" folder and put the file custom.css  inside  it seems work like this now
