### ISSUE TITLE
php 8 bug language selector - 0 syntax error, unexpected token "\"

### ISSUE THREAD

**Issue by ssnobben** [JoomShaper/helix-ultimate#146]
There is a bug for php 8.0.2 and multilanguage selector J 3.9.25. 

When you click on the Joomla language selector you got error. It works with php 7.4.16

It doesnt work and give you 

0
syntax error, unexpected token "\"

**Comment by ahamed** [comment]
The issue comes from the mighty `SP Page Builder`. Please wait for the next update of the `Page Builder` and till then use a lower PHP version (php <  8.0).

**Comment by mdamjadrana** [comment]
Already solved it was sp page builder issue.
