### ISSUE TITLE
Beta2 duplicated template style

### ISSUE THREAD

**Issue by APOODesign** [JoomShaper/helix-ultimate#147]
When editing a duplicated template style the changes won't save!

Joomla 3.9.26
PHP 7.4.16

**Comment by nadird** [comment]
i have the same issue, it saves but doesn't work

**Comment by APOODesign** [comment]
Tested it again with fresh install of Joomla 3.9.26  and HU 2 beta 3 version, but bug is still there.

**Comment by mdamjadrana** [comment]
Already Solved. Please check again
