### ISSUE TITLE
layout menu custom choice

### ISSUE THREAD

**Issue by gourou69** [JoomShaper/helix-ultimate#151]
when you select custom  its not possible to define custom number of columns no popup or something like this .

**Comment by mdamjadrana** [comment]
Can you please tell us details.

**Comment by stevel4857** [comment]
I had a similar issue. I believe he just wants to choose a menu option and then be able to customize the menu after choosing. 

In Gantry5 they have a spacer module. So, you can go full width and use empty spacers. I went to layout and added a custom block called header and manually added two blocks called logo and menu. The spacer issue I used by using an empty position1 and position2. If a block was created as "Spacer" that would be easy to understand.

**Comment by gourou69** [comment]
finally the option is there but just  you need to fix  the vertical scroll bar, it doesn't  appear so you dont see this custom layout  option unless you use keyboard's arrows
