### ISSUE TITLE
Animation Not Working

### ISSUE THREAD

**Issue by yofiesetiawan** [JoomShaper/helix-ultimate#152]
Hi,

Sorry, i use Helix Ultimate 2.0 Beta 2, i have problem of animation not working on every page. From what i found, it's because i disable the "PREDEFINED HEADER", from template settings. Because i don't find a header layout format with logo on left (corner), and menu on right (corner). So i forced to use NAVIGATION addon from SP Page Builder.

My question now, how to make the animation work normal, even when i disabled the "PREDEFINED HEADER"?

I also found that when i use SP Page Builder with Module Position (I tried to create new module position HEADER), this way i don't need to add same SECTION on every page, but the problem is, the STICKY feature on NAVIGATION ADDON is not working.

https://yopdesign.com/dev/idenyaflux/

Thank you very much....

**Comment by stevel4857** [comment]
I have also had this issue with the menu in a module using SPPagebuilder. It loses the sticky feature. To get mine to work I had to copy the CSS from the CSS file and paste it into the custom CSS section.

**Comment by mdamjadrana** [comment]
Header animations are related to the predefined header. So if you disable it. it won't affect others places.
