### ISSUE TITLE
Custom.css is overwritten by Sppagebuilder.css

### ISSUE THREAD

**Issue by LukeLake79** [JoomShaper/helix-ultimate#153]
Hi, I'm an Helix Ultimate Template user. Everything works fine in SP Page builder but on the other pages (those not made by SP page builder) the Custom.css file is loaded before Sppagebuilder.css so all classes that I try to change (for example in modules made by sppb) don't work. Custom.css is overwritten by Sppagebuilder.css. I think it could be a good improvement if Custom.css to be read as last in every page (inside and outside sp page builder pages).

**Comment by mdamjadrana** [comment]
I saw it working perfectly. all custom css file loaded in the end of head tag.
