### ISSUE TITLE
Issues I have noticed with HelixUltimate 2.0.0 beta 2

### ISSUE THREAD

**Issue by stevel4857** [JoomShaper/helix-ultimate#154]
I noticed that when I created a Custom Style on Presets and then turn it off and test the eight generic presets they are still over ridden by the the custom presets. Also, when I went to change the background color of the dropdowns I had serious problems making that work. I assume its a conflicting CSS issue already being addressed but want you to be aware.

Also, I'm not sure where to put feedback or feature request. But, Baic > Menu section you have these cool Predifined Headers. I assumed based on the other layouts that I could clcik on a Predefined Header and the modify it but it appears this isn't the case. I would like to be able to move items areounud, turn them on and off if needed and adjust style. Also, under sticky menu if I could change the CSS of the color as the sticky menu scrolls down that would be cool. My thought is to make the background color of the menu slightly transparent so people can see through the menu as they scroll. Also, since I am mentioning that adding transparency to each hex color would be great, like you have in SPPagebuilder.

Other thing, the ability to turn off Layout blocks would be nice. Just to see the layout with it off and possible hide, show based on mobile or desktop right there like SPPagebuilder.

**Comment by mdamjadrana** [comment]
It works fine. maybe you face cache issue.
