### ISSUE TITLE
[2.0.0-beta.2] New Joomla Admin UI repaint will cause inconsistent displaying of version of template

### ISSUE THREAD

**Issue by Bond97** [JoomShaper/helix-ultimate#157]
**Steps to reproduce issue**
1. Install latest nightly build of Joomla 4.0.0-beta8-dev;
2. Go to `System`->`Site Template Styles`- `shaper_helixultimate - Default`;
3. See some inconsistent displaying version text.

Screenshot is attached below.
![изображение](https://user-images.githubusercontent.com/78050514/117375009-ea2d3e00-aed6-11eb-844c-c239f91d4c6c.png)

Note: Joomla Admin UI repaint is merged today at PR https://github.com/joomla/joomla-cms/pull/33100

**Comment by ssnobben** [comment]
Any comments devs? ( +2 months ago today )

**Comment by joomleb** [comment]
Hi guys,
@ahamed @mi-prakash
as far as I read this ticket with last 2.1.1 release is solved and could be closed,
Please, Can you confirm?
