### ISSUE TITLE
[2.0 Beta 3] Add and edit preset colors preset.xml

### ISSUE THREAD

**Issue by leoalv** [JoomShaper/helix-ultimate#160]
First of all thanks for the best framework for Joomla.
Helix in its version 3 and ultimate 1.x are very flexible when it comes to adding new color names (color fields) in each preset and even in custom colors. Many of us have taken advantage of that to create a template with 2 or 3 main colors.

Now in version 2 of Helix Ultimate, you have added a great feature which is the editing of the presets, but you cannot edit the new color names that are imported from previous versions of helix, because the preset editor gets the list colors from `/plugins/system/helixultimate/src/form/preset.xml`. For example, since helix 3 I have the following color names `primary_color`, `secondary_color` that are absolutely necessary, and I think that many of us who have worked with Helix have added color names and we are going to face this problem.

Question: is there a way to override `preset.xml` so that we can add our own color names? If it does not exist, I would like to add the options to create the override from the template.

Thank you guys, you are great, I hope your answers make decisions.

**Comment by ssnobben** [comment]
Any comments devs? ( 29 days ago today )

**Comment by mdamjadrana** [comment]
If you need any custom variables for color or anything in scss. you can easily create custom variables in custom scss files. I think it will solve your problem.

**Comment by leoalv** [comment]
No, that does not solve the problem.
If the user wants to modify the colors from the HELIX panel, the color that I have added with SCSS will not be able to change unless the user also edits the SCSS file, and if we think of template updates, all those changes in the SCSS file and CSS will be lost. If you are going to use SCSS for colors, editing presets doesn't make sense.

Why don't they want to change? if you need to add a condition that verifies the existence of the preset.xml file within the template, if it exists it loads that one, if it does not exist it loads the one that comes with the template. In fact I did tests and it works perfectly, but if I deliver modified helix in an update that condition will be lost.

**Comment by leoalv** [comment]
I request that this case be reopened, you cannot close it without it being resolved. I would gladly send you the code in PR but it is also vain, they never review it.
