### ISSUE TITLE
[2.0 Beta 3] Typograpy color field

### ISSUE THREAD

**Issue by leoalv** [JoomShaper/helix-ultimate#162]
The presets are the color control, you have added the color field in the sources which is an excellent feature if you want to change the color easily. Currently this field is auto filled with black color `#000000` that is defined in the `renderFontColor()` function. In my opinion it should not be autocompleted, because if it is assumed that in the PRESETS I already select the color for the body `#454545`, when activating the font for the body that is overwritten by `#000000`, if I delete this color, in the next edition is autocomplete again. The same happens for Navigation font type, in the headings as well but it is understandable because there is no specific color for it in the PRESETS. The only current solution is to add the same color codes in both the preset and the Typography.

The recommendation is not to autocomplete and take the values from the CSS files as it is done with the fontWeight, fontSize and other fields.

Thank you.

**Comment by ssnobben** [comment]
Any comments devs? ( 28 days ago today )

**Comment by mdamjadrana** [comment]
If you need any custom variables for color or anything in scss. you can easily create custom variables in custom scss files. I think it will solve your problem.

**Comment by leoalv** [comment]
It is really disappointing that they close a well explained case, and the saddest thing is that the solution to that problem is easy, they just have to remove the autofill color.

Assuming that in SCSS I put the color` #555555` `for the body body{color:#555555;}`, the template automatically generates color` #000000` for the body, **if you know CSS you will understand that the inline values overwrite those of the files.**

I request this case be reopened because what you mention does not give a solution and less correct the BUG.

PS: You guys are already acting like the Joomlart guys, kicking the feedback from the community
