### ISSUE TITLE
[2.0.0-beta.3, SPPB 3.7.10] Custom.css files new code entries ignored

### ISSUE THREAD

**Issue by BurnHard1to1** [JoomShaper/helix-ultimate#164]
SPPB recently updated to 3.7.10. Worked fine so far but yesterday I noticed that new code inserted in custom.css files is ignored. Inspecting code shows former versions of custom.css files inspite of having saved properly and emptied cache several times.

Files are also linked properly, eg.

`<link href="/templates/shaper_helixultimate/css/custom/custom_responsive.css" rel="stylesheet" />`

Inserting custom code into the template´s custom css code field does the job, but this is a workaround, not a solution.

**Comment by mdamjadrana** [comment]
I saw that it works fine in my localhost. Is it localhost or live server?

**Comment by BurnHard1to1** [comment]
hi amjad, this is on a live server. worked fine until the latest updates

**Comment by mdamjadrana** [comment]
I also tested in live server it works perfect. Maybe you face cache issue.
