### ISSUE TITLE
Issue Since Update To Version 1.1.3: Colors Not Managed Correctly When Compiling SCSS

### ISSUE THREAD

**Issue by woluweb** [JoomShaper/helix-ultimate#165]
Hi,

This issue refers to https://www.joomshaper.com/forum/question/4115#qa-answer-18954
[as asked by Toufiq, I create an issue here so that it can be solved more easily ]

I summarize it hereafter.
Txs in advance for the fix ;)

---

I have investigated further on my side. And I do confirm that there is some kinf of issue when Helix Ultimate compiles SCSS (when using for example rgba and lighten).

See the following example (which I have added on my live website mentioned above so that you can see for yourself) :

```
$joomshaper: #69aa41;
$joomshaper-rgba: rgba($joomshaper, 0.5);
$joomshaper-lighten: lighten($joomshaper,20%);
```

```
.joomshaper {background: $joomshaper};
.joomshaper-rgba {background: $joomshaper-rgba};
.joomshaper-lighten {background: $joomshaper-lighten};
```
Test it with https://www.sassmeister.com/, it compiles nicely into

```
.joomshaper {background: #69aa41;}
.joomshaper-rgba {background: rgba(105, 170, 65, 0.5);}
.joomshaper-lighten {background: #9fcf82;}
```
But in https://www.healthybelgium.be/templates/shaper_helixultimate/css/template.css?2105275327 it compiles into

```
.joomshaper {background: #69aa41;}
.joomshaper-rgba {background: rgba(#69aa41, 0.5);}
.joomshaper-lighten { background: lighten(#69aa41, 20%);}
```
So I guess there is a problem somewhere in the SCSS/SAAS compiler coming along with Helix Ultimate :)

**Comment by woluweb** [comment]
Hi guys. Any news on this?
(was reported 8 days ago on https://www.joomshaper.com/forum/question/4115)
Txs !

**Comment by Astarhan** [comment]
Hello. I have experienced the same problem. Is there a solution on the way? My current workaround is to copy my .scss file to https://www.sassmeister.com/ an save a custom.css ...

**Comment by mdamjadrana** [comment]
SCSS compiler issue fixed.
Please update to helix 1.1.4

**Comment by woluweb** [comment]
Txs a lot. I do confirm that it works.
Btw, is there any way to have a custom.scss ? (apart from manually editing master.scss to add an import... and have it overwritten everytime there is an update of Helix)

**Comment by mdamjadrana** [comment]
yeah, it's possible in version 2.0.
