### ISSUE TITLE
Component area for desktop has wrong col-lg-X class

### ISSUE THREAD

**Issue by altrasoluzione** [JoomShaper/helix-ultimate#166]
Hi!
I've just realized that in Helix Ultimate 2.0 Beta 3, changing the Main Body Component area to any other value (the example is for 9 columns, hiding left aside, expecting col-lg-9) for Smaller Desktop, the output seems to be **stuck at col-lg-6** while setting aside panels values, even for col-lg is ok (please see first two screenshots).

![Component area settings](https://user-images.githubusercontent.com/22329855/121147939-a1ec9d00-c841-11eb-9e0e-0fa16c9d0aec.png)
![Component area results](https://user-images.githubusercontent.com/22329855/121147955-a4e78d80-c841-11eb-897c-ef71b790c7ea.png)

I've also tried with a **fresh Joomla installation** but setting left, component and right at 2+8+2, output shows a **col-lg-4** instead of col-lg-8 (please, see last two screenshots).

![Fresh Joomla installation Settings](https://user-images.githubusercontent.com/22329855/121182034-f48a8100-c862-11eb-9284-b379ea40ab02.png)
![Fresh Joomla installation Results](https://user-images.githubusercontent.com/22329855/121182045-f7857180-c862-11eb-89fe-fee7ab122b1f.png)

Am I missing something?

Thank you very much
Kind regards

**Comment by ssnobben** [comment]
Any comments devs? ( 7 days ago today )
