### ISSUE TITLE
Joomla 4. undefined method Joomla\CMS\HTMLHelper::getJSObject()

### ISSUE THREAD

**Issue by ReLater** [JoomShaper/helix-ultimate#167]
From a report on joomla.forum.de:

> I tried the current Helix template (https://www.joomshaper.com/blog/helix-ultimate-2-0-beta-3) for Joomla 4. Unfortunately, most of the positions are not accepted, resp. acknowledged with an error. Call to undefined method Joomla\CMS\HTMLHelper::getJSObject() For example, if I set the login module to the position 'left'.

I assume it is this line:

https://github.com/JoomShaper/helix-ultimate/blob/v2.0.0-beta.3/templates/shaper_helixultimate/html/layouts/libraries/cms/html/bootstrap.php#L353

Method getJSObject() has been removed from Joomla 4.

**Comment by ssnobben** [comment]
Any comments devs? ( 5 days ago today )

**Comment by mdamjadrana** [comment]
Solved

**Comment by ReLater** [comment]
Thank you! I reported the solution in the forum.

> "Change line like this": https://github.com/JoomShaper/helix-ultimate/commit/a0d0c1495137fb23372c472382a5a93a2fe1b0e9
