### ISSUE TITLE
logo image src problem 

### ISSUE THREAD

**Issue by nadird** [JoomShaper/helix-ultimate#168]
Hi i noticed a little problem in beta 3 multilangual website 
the src link of logo image includes language code here 
```
<div class="logo"><a href="/">
<img class='logo-image '
					srcset='https://evact.fr/images/logo.svg 1x, '
					**src='images/logo.svg'**
					alt='Evact Algérie'
				/>
</a></div>

```
and this crates a 404 response because it calls `https://evact.fr/fr/images/logo.svg` instead of `https://evact.fr/images/logo.svg `

**Comment by ssnobben** [comment]
Yes the logo dont need different logos for different langauges? But if I have a logo with different langauge text for different markets in the world?....

what you think? its a setting with Joomla system langauge plgs that have settings too. Did they have any effect?

**Comment by nadird** [comment]
> Yes the logo dont need different logos for different langauges? 
The problem is not changing logo by changing language, but there is a problem in the logo image path thats all. 
to change the logo by changing the language you will have to modify the logo.php file in the template and make an if then else by testing $lang and providing a link for each language.

**Comment by mdamjadrana** [comment]
I checked it works fine.
