### ISSUE TITLE
Off Canvas menu improvement towards WCAG 2.0 AA compliance

### ISSUE THREAD

**Issue by dynamicsites** [JoomShaper/helix-ultimate#170]
In order to make the Off Canvas menu compliant to the WCAG 2.0 AA standard, small changes need to be made to 2 files inside the template structure.

1) file templates/shaper_helixultimate/features/menu.php

Change all 3 i tags (Font awesome icons) to spans, lines 37, 48 and 56. Titles should also be added to their parent a tags (anchor links), for this I suggest you just copy the existing JText::_('HELIX_ULTIMATE_NAVIGATION');

```
		$output = '';

		if($menu_type == 'mega_offcanvas')
		{
			$output .= '<nav class="sp-megamenu-wrapper" role="navigation">';
			if($offcanvs_position == 'right') 
			{
				$output .= '<a id="offcanvas-toggler" title="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'" aria-label="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'" class="offcanvas-toggler-right" href="#"><span class="fa fa-bars" aria-hidden="true" title="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'"></span></a>';
			}
			$menu = new HelixUltimateMenu('d-none d-lg-block','');
			$output .= $menu->render();
			$output .= '</nav>';
		}
		elseif ($menu_type == 'mega')
		{
			$output .= '<nav class="sp-megamenu-wrapper" role="navigation">';
			if($offcanvs_position == 'right') 
			{
				$output .= '<a id="offcanvas-toggler" title="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'" aria-label="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'" class="offcanvas-toggler-right d-block d-lg-none" href="#"><span class="fa fa-bars" aria-hidden="true" title="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'"></span></a>';
			}
			$menu = new HelixUltimateMenu('d-none d-lg-block','');
			$output .= $menu->render();
			$output .= '</nav>';
		} else {
			if($offcanvs_position == 'right') 
			{
				$output .= '<a id="offcanvas-toggler" title="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'" aria-label="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'" class="offcanvas-toggler-right" href="#"><span class="fa fa-bars" aria-hidden="true" title="'. JText::_('HELIX_ULTIMATE_NAVIGATION') .'"></span></a>';
			}
		}

		return $output;
```

2) file templates/shaper_helixultimate/index.php

Add a title to the a tag (anchor link) in line 150 once again copying the already existing JText::_('HELIX_ULTIMATE_NAVIGATION');

```
<!-- Off Canvas Menu -->
    <div class="offcanvas-overlay"></div>
    <div class="offcanvas-menu">
        <a href="#" title="<?php echo JText::_('HELIX_ULTIMATE_NAVIGATION'); ?>" class="close-offcanvas"><span class="fa fa-remove"></span></a>
        <div class="offcanvas-inner">
            <?php if ($this->countModules('offcanvas')) : ?>
                <jdoc:include type="modules" name="offcanvas" style="sp_xhtml" />
            <?php else: ?>
                <p class="alert alert-warning">
                    <?php echo JText::_('HELIX_ULTIMATE_NO_MODULE_OFFCANVAS'); ?>
                </p>
            <?php endif; ?>
        </div>
    </div>
```

I haven't noticed any layout issues resulting from these changes (template version 1.1.4), they are pretty subtle anyway.

I use this tool to check website's WCAG compliance => https://achecker.achecks.ca/checker/index.php

**Comment by joomleb** [comment]
@dynamicsites @mi-prakash @ahamed 
Hi guys,
What about the last Helix Ultimate 2.1.1 release & WCAG compliance ?

- [Siteimprove](https://www.siteimprove.com/glossary/wcag-compliance-checker/#:~:text=You%20could%20comb%20through%20the,your%20website%20for%20WCAG%20compliance)
- - [Accessibility Checker](https://www.accessibilitychecker.org/)

**Comment by dynamicsites** [comment]
> @dynamicsites @mi-prakash @ahamed Hi guys, What about the last Helix Ultimate 2.1.1 release & WCAG compliance ?
> 
>     * [Siteimprove](https://www.siteimprove.com/glossary/wcag-compliance-checker/#:~:text=You%20could%20comb%20through%20the,your%20website%20for%20WCAG%20compliance)
> 
>     * [Accessibility Checker](https://www.accessibilitychecker.org/)
> 
> 
> PS the #159 seems to be the same...

According to https://wave.webaim.org/ 2.1.1 is fine, as long as your part of the website (colors, content structure etc) is up to spec.

**Comment by joomleb** [comment]
@dynamicsites 
Thank you for your reporting.
Please, Can you close the ticket?

OR
@mi-prakash @ahamed 
Can you close the ticket as solved ?
