### ISSUE TITLE
[2.0 beta 2 & 3] missing icons for drop-down menus

### ISSUE THREAD

**Issue by pchelpbg** [JoomShaper/helix-ultimate#172]
After an upgrade I found that the icon for down arrow (on all drop-down menus) has gone, while the template still tries to use it. Fixed the issue by revert-updating to beta 1. Beta versions 2 and 3 have the issue, prior to that (incl. beta 1) are OK on this.

(up to beta 1):
![Screenshot 2021-06-17 at 21-15-16 Оряхово - Екскурзии](https://user-images.githubusercontent.com/86076227/122454089-a63c5700-cfb3-11eb-95a6-672d7415fa89.png)
(beta 2, beta 3):
![Screenshot 2021-06-17 at 21-15-39 Оряхово - Екскурзии](https://user-images.githubusercontent.com/86076227/122454093-a6d4ed80-cfb3-11eb-940a-85e7dcf73458.png)

**Comment by mdamjadrana** [comment]
Check font awesome on/off option. Maybe font awesome disabled.

**Comment by pchelpbg** [comment]
Thank you, I'll check it today. However, I doubt if that's the issue because I didn't make any changes on the Helix configuration - just upgraded to the newer version (and uploading the old Beta 1 fixed the problem, again - with no change on any settings).
