### ISSUE TITLE
500 Icon::print_popup Not Found

### ISSUE THREAD

**Issue by HDInfautre** [JoomShaper/helix-ultimate#173]
Hello 
I was asked to move my comment here.
I have this error https://joom4test.88h.ovh/index.php?option=com_content&view=article&id=1&Itemid=118 while I did nothing special. Joomla 4 RC2 with some extensions 
Regards

**Comment by mdamjadrana** [comment]
How do you confirm that this issue comes from helix? 
IT's maybe come from others' extension.
If you sure it's from helix tell us details.

**Comment by HDInfautre** [comment]
Hello
It works with cassiopa or t4 templates
I made different tests.
Do you want an access to the administration?

**Comment by mdamjadrana** [comment]
Already solved. test it.
[2.0.0-rc.2.zip](https://github.com/JoomShaper/helix-ultimate/files/6700939/2.0.0-rc.2.zip)

**Comment by HDInfautre** [comment]
hello
I have downloaded and installed (twice) the rc2-dev file.
I have the same problem!
I see that the name is rc1!
Shaper_helixultimate  2.0.0-rc.1
Is it the right file?
Do you want to access it?

**Comment by mdamjadrana** [comment]
Please share your access. my mail address mdamjadrana@gmail.com

**Comment by mdamjadrana** [comment]
Solved, Check now.

**Comment by HDInfautre** [comment]
ok thanks
Is this a bug?
what was the problem?

**Comment by Orgoth** [comment]
In Joomla 4.x, the Joomla-Developers removed the Print-Button without a replacement.  
As a result, the template threw an error because it could no longer find the icon.  
The developer "@mdamjadrana" has now added a query that ensures that the icon and button will only be displayed in versions smaller than 4.x.  

```
<?php if ($params->get('show_print_icon') && JVERSION < 4 ) : ?>
    <?php echo HTMLHelper::_('icon.print_popup', $this->item, $params); ?>&nbsp;
<?php endif; ?>

If this is of interest to you, I have opened a feature request in the forum with the request that a print button be provided by the template.  
This also avoids compatibility problems with the template itself.  

https://www.joomshaper.com/forum/question/14688

Have a nice day
