### ISSUE TITLE
Problem with scroll bars in offcanvas menu

### ISSUE THREAD

**Issue by sitte** [JoomShaper/helix-ultimate#174]
There is a problem with the behaviour of the mobile menu. 
When you open the offcanvas menu and scroll down the page, the content is wider than the screen and scroll bars appear. 
Video showing the behaviour of the website: https://youtu.be/MvIey08-y2k

How to reproduce:
I'm testing on official demo: http://demo.joomshaper.com/2018/helixultimate/
1. It happens only if You use website on mobile phone or if You set specific device on developer console on firefox. Problem does not appear if You set small resolution but do not set device in developer console.
2. If You open side menu and drag screen down or right or if You scroll down then website canvas size exceeds screen size and scrolls appear. 
3. It does not appear if You set menu to show on right.

**Comment by sitte** [comment]
Some solution:

```
@media (max-width:991px){

	body.ltr.offcanvs-position-left.offcanvas-active .body-wrapper {
		width: calc(100% - 300px);
		overflow: hidden;
		
	}

	body.ltr.offcanvs-position-left.offcanvas-active .body-innerwrapper {
		width: 100vw;
	}
}
```

**Comment by mdamjadrana** [comment]
It's not an issue
