### ISSUE TITLE
Error Page (view) - HU 2.0 RC1

### ISSUE THREAD

**Issue by Pawel-Support** [JoomShaper/helix-ultimate#177]
In the head section of the website I see broken code
 
< link href="/templates/shaper_helixultimate/css/presets/{"footer_link_hover_color":"#FFFFFF","footer_link_color":"#A2A2A2","footer_text_color":"#FFFFFF","footer_bg_color":.....`

only in Error Page (404 for example)

**Comment by ssnobben** [comment]
Nobody home?

**Comment by joomleb** [comment]
Hi guys,
@Pawel-Support @ahamed @mi-prakash
Can we consider this ticket as "solved" with last 2.1.1 release ?
Please, Can you confirm it?
