### ISSUE TITLE
Important Bug: Template Copy - No separate settings  [RC1]

### ISSUE THREAD

**Issue by Pawel-Support** [JoomShaper/helix-ultimate#179]
I noticed when I duplicated a template - that 2nd template (clone) still uses a setting from the original template, it's not possible to make them unique. Even if you see them in template options - they are not used on the front-end. Mostly problem is related with header area, 

In previous Helix Ultimate 1.1.4  is working correctly.

**Comment by mdamjadrana** [comment]
It's working fine. Maybe you did some wrong.
