### ISSUE TITLE
Helix Ultimate 2.0 RC 1

### ISSUE THREAD

**Issue by wilsongsjunior** [JoomShaper/helix-ultimate#180]
Hi, I see this bug:
Multiple template styles with Shaper_helixultimate do not work when assigned to different menus. The default template Shaper_helixultimate takes precedence over the others.

**Comment by mdamjadrana** [comment]
issue solved.

https://github.com/JoomShaper/helix-ultimate/commit/63b64631bbe51f011f03c7fa87a69aae3e3d333c
