### ISSUE TITLE
Custom header bugs

### ISSUE THREAD

**Issue by Rakeshmvd** [JoomShaper/helix-ultimate#183]
1 BUG. The Predefined Headers are nice but still not one of them have Multi-Language  setup in mind.

Creating my own Custom Header menu there is a problem when setting the menu to RIGHT:
The Burger Icon is not being displayed when having the Off Canvas Position set to RIGHT
<-! if offcanvas position right -->  NOT BEING SHOWN within Header Row.

#sp-header nav.sp-megamenu-wrapper #offcanvas-toggler
Is set to Display: none   ???

(There was similar problem with Helix Ultimate 1.0)

2 BUG. Menu items ONLY being displayed when using Top 1 and Top 2 inside the third layout column

3. Please add new Module Position "Language" for the Custom Layout Column options. VERY IMPORTANT
This will help making the site multi-language ready, for the language switch module.

4. Add a predefined header or Multi-language site, incorporation the Language switch module position.

Helix Ultimate 2.0RC

**Comment by pavel-ww** [comment]
> Please add new Module Position "Language" for the Custom Layout Column options.

You can create any number of new module positions with any names as you like. Read Helix Documentation

**Comment by Rakeshmvd** [comment]
> > Please add new Module Position "Language" for the Custom Layout Column options.
> You can create any number of new module positions with any names as you like. Read Helix Documentation

Yes but my suggestion is to make it standard, since adding a custom Module Position within the Template Style is cumbersome and it is a much needed module position for multi-language sites.

**Comment by Rakeshmvd** [comment]
Also the Helix Documentation, is currently not explaining adding Custom Module Positions anymore.

**Comment by joomleb** [comment]
Hi guys,
@Rakeshmvd 
This is the "brother" of #185
Am I right ? 
With the last 2.1.1 release and [its Documentation](https://www.joomshaper.com/documentation/helix-framework/custom-header) we can consider this as "solved", Right ?

@ahamed @mi-prakash
as far as I read this ticket should be closed, Shouldn't it?
