### ISSUE TITLE
Add Custom CSS fieldbox in template style

### ISSUE THREAD

**Issue by Rakeshmvd** [JoomShaper/helix-ultimate#185]
Custom CSS should be quickly accessible:

At the moment these are the needed clicks: 
1. Joomla Templates Styles: shaper_helixultimate - Default
2. Template Options button
3. Custom Code button
4. Scroll down to Custom Code fieldbox

Please change this to:

1. Joomla Template Styles: shaper_helixultimate - Default
2. Click tab Custom Code (next to Menu Assignment) [suggestion to create new tab custom code with the fieldbox custom code in it]

Custom code access need to be much more easy to be accessed.

Helix Ultimate 2.0RC

**Comment by pavel-ww** [comment]
Hi Rakeshmvd. If you allow, here is my private opinion about this. Using Custom CSS Field In Template Settings, this is a bad practice, as adds code to Head. Therefore, I think, let it stay where there is now. Use the custom.css file for your code.

**Comment by Rakeshmvd** [comment]
> Hi Rakeshmvd. If you allow, here is my private opinion about this. Using Custom CSS Field In Template Settings, this is a bad practice, as adds code to Head. Therefore, I think, let it stay where there is now. Use the custom.css file for your code.

Ofcourse custom,css should stay, but custom css within the Template Styles is more simple to access, and my suggestion is simply an alternative way to access it more quickly.  But a editor window for the custom.css file would be a great addition as well ( as a third tab)

**Comment by pavel-ww** [comment]
> But a editor window for the custom.css file would be a great addition as well ( as a third tab)

I can recommend you a better approach for this. Just use the desktop code editor, such as Notepad++ or VS Code connected to your site via FTP. It is much more convenient than using the code editors available in Joomla.

**Comment by ahamed** [comment]
Hello @Rakeshmvd,
I fully agree with @pavel-ww. The custom field is not a good option to add a good amount of CSS. If you need to add more CSS then write the code into `custom.css` file.

In this version, you can do more. Just create a folder named `custom` inside the `templates/shaper_helixultimate/css/` directory and add whatever CSS file there. The CSS files would be added to the site.

**Comment by joomleb** [comment]
Hi guys,
@ahamed @mi-prakash 
as far as I read this ticket should be closed, Shouldn't it?
