### ISSUE TITLE
Parent Column button in SP Page Builder 3.7.12 bug after install HU rc2

### ISSUE THREAD

**Issue by wilsongsjunior** [JoomShaper/helix-ultimate#187]
Awesome! Excite to final version.
Something wrong in SP Page Builder 3.7.12 after install HU rc2. The "Parent Column" button in add-on options. Page reload with homepage when it is clicked. This happens on my localhost.

**Comment by ssnobben** [comment]
Nobody home?

**Comment by joomleb** [comment]
Hi guys,
@ahamed @mi-prakash
as far as I read this ticket with last 2.1.1 release is solved and could be closed,
Please, Can you confirm?

**Comment by mi-prakash** [comment]
yes, closing the issue
