### ISSUE TITLE
Module position right disappears - HU 2.0 RC2

### ISSUE THREAD

**Issue by mac-joomla** [JoomShaper/helix-ultimate#188]
After Updating to from HU 2.0 RC1 to HU 2.0 RC2 module position "right" does not show anymore.

Thank you and best regards. mac-joomla

**Comment by ssnobben** [comment]
Nobody home?

**Comment by ahamed** [comment]
This issue is fixed along with issues #190 & #196.

**Comment by joomleb** [comment]
Hi guys,
@ahamed @mi-prakash 
as far as I read this ticket is solved and should be closed, Shouldn't it?
