### ISSUE TITLE
Position right not working

### ISSUE THREAD

**Issue by Aidan38** [JoomShaper/helix-ultimate#190]
Hello,

I try Helix Ultimate 2.0.0-rc.2.
When I publish a module on the right position, the module is displayed on the middle of the page instead off on the right sidebare.

<img width="1586" alt="helix-1" src="https://user-images.githubusercontent.com/20039918/126993675-73082829-d539-484e-bfa6-917f55bd3b62.png">

**Comment by ahamed** [comment]
@ssnobben,
We were all at home 😄 . It's COVID time.

**Comment by ssnobben** [comment]
> 
> 
> @ssnobben,
> We were all at home 😄 . It's COVID time.

Thats good bcs tomorrow is prime time for Joomla 4 (incredible) release and then we will put fire in your butt to also upgrade Helix Ultimate v 2 and SP Pagebuilder Pro 4 for Joomla for compability lol

**Comment by joomleb** [comment]
Hi guys,
@ahamed @mi-prakash 
as far as I read this ticket is solved and should be closed, Shouldn't it?
