### ISSUE TITLE
Unable to edit template script issue

### ISSUE THREAD

**Issue by brittambrose** [JoomShaper/helix-ultimate#192]
<img width="2004" alt="image" src="https://user-images.githubusercontent.com/7391687/127815247-87e42db5-317a-4f9f-9efd-fee97b64dcb8.png">

I'm attempting to give Helix Ultimate 2 (beta 3) a test in J4, but for the life of me cant' edit the template settings menu.

After a VERY long load time, the left menu shows - but when I click nothing happens? 
So no fly-out, not able to open any of the settings, basic, layout, advanced etc or any of the usual setting functions I can in Helix Ultimate on J3.

I have tested in both Chrome and Firefox, the same result.

There appears to be a script conflict as shown in the screen shot.

**Comment by ssnobben** [comment]
Nobody home?

**Comment by brittambrose** [comment]
I was asked to post this in git by Joomshaper, to be honest I'm a designer with a small degree of technical capability compared to some, deciphering code and errors is not my strength, if something is very obvious and I have missed it - please let me know. Or if I need to provide more information also let me know.
I am on Mac - Big Sur 11.4

**Comment by ahamed** [comment]
Hello @brittambrose,
Is the issue still persisted? Did you try clearing your cache? Please try clearing the browser cache as well. For clearing browser cache (at chrome) open developer console -> right-click the reload button -> select `Empty cache and hard reload` option.

**Comment by brittambrose** [comment]
Hi Ahamed,
I am an experienced Joomla user  and I have performed all the obvious things such as  as clearing cache. My team in Greece has also logged in an experienced this same very slow to load and unable to edit issue.
When I have time I can try a complete reinstall (however I also have done this 3 times as well), are there any updates to the last version you have made available? Can you please send me a link to this updated version.
Also note this has been tested across three browsers also.
Hopefully you have some insights?
Thanks
Britt

**Comment by brittambrose** [comment]
This has been done with no change. I will attempt a 4th reinstall if you can please send me a updated latest version link of Helix.

**Comment by ahamed** [comment]
I've tested `Helix-2.0.0-rc.2` with `Joomla-4.0.0-rc.6`. I cannot recreate the issue. Did you try `Helix-2.0.0-rc.2`?

**Comment by brittambrose** [comment]
I have cleared and reset all I can...and still no joy...perhaps it is something very simple...here are the error messages with the J4 Stable and Helix applied. 
Also I have checked as a comparison - there are no errors with Cassopia Template added as a comparison. I have added back the Helix - so that you may be able to preview and inspect in console your end.

Are there any uniquely different PHP settings I need to have?...I can provide you cpanel access or admin access if you are interested in looking into more deeply.

The errors are only showing in the admin template edit view (not on the front end of the live site)

<img width="611" alt="image" src="https://user-images.githubusercontent.com/7391687/129834231-fe3813df-4772-44dd-861b-16efb4e20669.png">

Thanks
Britt

**Comment by brittambrose** [comment]
I have further discovered it was Cloudflare SSL settings blocking the template editing.
I'm attaching the SSL setting needed in case you need to add this to your FAQ's.

![image](https://user-images.githubusercontent.com/7391687/129856226-d05d0fdc-2c18-4ebb-9985-7117a7affe96.png)

On older Helix templates I have only used Flexible, but for this new version with J4, it must be Full.

**Comment by ahamed** [comment]
>I have further discovered it was Cloudflare SSL settings blocking the template editing.
I'm attaching the SSL setting needed in case you need to add this to your FAQ's.

Thanks for your response.
