### ISSUE TITLE
Mega menu builder missing

### ISSUE THREAD

**Issue by benyrfg** [JoomShaper/helix-ultimate#193]
Helix Ultimate 2.0.0 RC2 - Mega menu builder missing.
Joomla! 3.9.28  

![Screenshot (12)](https://user-images.githubusercontent.com/16369993/127840894-b897c723-accb-410b-a75d-745d995fa41d.png)

**Comment by ahamed** [comment]
We've moved the mega menu settings to the `menu` section of the template settings.
![image](https://user-images.githubusercontent.com/5783354/127842262-0db8b173-f57f-4079-8db6-fcc57d46bf79.png)
![image](https://user-images.githubusercontent.com/5783354/127842338-b0284f69-d87e-4246-8d49-bb71bdf88ac4.png)

**Comment by benyrfg** [comment]
Oh, ok, good :)
