### ISSUE TITLE
Two Offcanvas icons

### ISSUE THREAD

**Issue by ChrisWST** [JoomShaper/helix-ultimate#200]
When I select to display only off-canvas at the Menu Type, I get two icons displaying on the right.
See here: https://prntscr.com/1qb51rn

**Comment by ahamed** [comment]
Are you using pre-defined header or header layout?

**Comment by ChrisWST** [comment]
No predefined header, I created my own layout: https://prntscr.com/1qvw9h5
And this is what is generated with these options: https://prntscr.com/1qvw9ge
I have hidden the -secondary in css as there is no use for it.

**Comment by joomleb** [comment]
Hi guys,
@ahamed @mi-prakash 
as far as I read this ticket with last 2.1.1 release is solved and could be closed, 
Please, Can you confirm?
