### ISSUE TITLE
Icon lists from Sp Page Builder do not work anymore on Helix Ultimate 2 and Joomla 4

### ISSUE THREAD

**Issue by ChrisWST** [JoomShaper/helix-ultimate#204]
Again, not sure if this is an issue regarding helix ultimate, but any Sp Page Builder addon using icons does not work anymore on Joomla 4 and Helix Ultimate 2.
See here: https://youtu.be/HUzijuTBJGk

**Comment by ahamed** [comment]
This issue is associated with SP Page Builder. I've forward your issue to the Page Builder team. Thanks for your issue.
