### ISSUE TITLE
featured article shows "expired"

### ISSUE THREAD

**Issue by Demel75** [JoomShaper/helix-ultimate#206]
If use featured article in the left upper corner it shows the text "expired". 

This is the generated sources:

> <div class="system-unpublished">
> <span class="label label-warning">Expired</span>

![image](https://user-images.githubusercontent.com/18624555/130188927-2d5ceba2-53cd-49ac-a5e1-848589149cc1.png)

**Comment by osijekdgo** [comment]
Change line 59 in the file /plugins/system/helixultimate/overrides/com_content/featured/default_item.php
with this code (comment PHP echo)
<span class="badge bg-warning text-light"><?php //echo Text::_('JEXPIRED'); ?></span>

Hope it will be fixed in next version

**Comment by matrix630307** [comment]
i have deinstalled the template and framework. then i have installed the 2.0.7 (framework 2.0.5). in this case, the bug is not present. after update the framework to 2.0.8, the message "Abgelaufen" will show. Can anyone help?

**Comment by prakash-a7x** [comment]
this issue is fixed on the latast update.
