### ISSUE TITLE
Import/Export still not working on version 2.0.1

### ISSUE THREAD

**Issue by ChrisWST** [JoomShaper/helix-ultimate#208]
Import/Export still not working on version 2.0.1, please check here: https://youtu.be/2DHSTfksupc

**Comment by ahamed** [comment]
@ChrisWST,
Could you please share your exported `JSON` file here?

**Comment by ChrisWST** [comment]
Sure, I attached it, it is from a template that has been updated from 1.1.4 version.
[appz_settings_24-08-2021.zip](https://github.com/JoomShaper/helix-ultimate/files/7040010/appz_settings_24-08-2021.zip)

**Comment by ahamed** [comment]
Thank you so much for your cooperation. Your issue has already been fixed. Please wait for the `2.0.2` version.

**Comment by ChrisWST** [comment]
I can confirm it is fixed.
