### ISSUE TITLE
Down arrow not rendering correctly for menu items with a submenu

### ISSUE THREAD

**Issue by persidis** [JoomShaper/helix-ultimate#210]
It was working perfectly with previous version of helix-ultimate but not anymore. Instead of an icon there's just an empty square box. My site is using Greek language, if it has anything to do with this issue.

![image](https://user-images.githubusercontent.com/5758435/130368808-db34202e-9cd1-43c2-93c4-dc97f171805a.png)

**Comment by persidis** [comment]
I enabled font awesome from template settings and it worked!

**Comment by izzyreal** [comment]
@persidis How did you enable font awesome?
