### ISSUE TITLE
Portfolio item does not work with Sp Page Builder integration

### ISSUE THREAD

**Issue by ChrisWST** [JoomShaper/helix-ultimate#211]
Sp Simple Portfolio item doesn't work anymore when using Sp Page Builder integration on Joomla 4 / HU2. I click on the button but nothing happens: https://www.youtube.com/watch?v=AZRhcw-lJEI

**Comment by ahamed** [comment]
This issue is not associated with Helix Ultimate. We've informed the Page Builder team.
Thanks for your issue.
