### ISSUE TITLE
Cannot create custom preset anymore

### ISSUE THREAD

**Issue by ChrisWST** [JoomShaper/helix-ultimate#213]
When creating new template in Helix Ultimate 1 I used to insert preset9 in options.xml and preset9.css in the presets folder. But now when I do so, Preset 9 does not appear in the preset options. Why is that?

**Comment by ahamed** [comment]
Good point. We'll fix that at the next patch.
Thanks.

**Comment by ChrisWST** [comment]
Fixed.
