### ISSUE TITLE
Error: Default Layout file is not exists! 

### ISSUE THREAD

**Issue by tonamphong** [JoomShaper/helix-ultimate#214]
I got the issue with: **Default Layout file is not exists! Please goto to template manager and create a new layout first.**
This is strange because some menu items working fine, but some menu items render the page error when clicking on it.

Screenshot: https://imgur.com/LuB8uCE

The render_layout function defined via https://github.com/JoomShaper/helix-ultimate/blob/master/plugins/system/helixultimate/src/Core/HelixUltimate.php (line 489)
If you print the result of $layout_file, you will receive the path like: /Users/your_name/Sites/joomla-root/templates/system/options.json

It should be: joomla_root_path/templates/template_name/options.json Right ?

One more, the shaper_helixultimate is hardcoded via https://github.com/JoomShaper/helix-ultimate/blob/master/plugins/system/helixultimate/src/Platform/Helper.php (line 468). It should be template ID? By changing to templateID we can avoid the issue with css/js compression(caching).

Thanks

**Comment by ahamed** [comment]
>It should be: joomla_root_path/templates/template_name/options.json Right?

You are right. It should be like this.

Could you please share your site URL as we can inspect the issue in depth.
Or could you please share __how to reproduce__ the issue,so that we can identify the issue.

**Comment by tonamphong** [comment]
Hi Ahmed,
I found the issue related to this case by checking the template_style_id for menu item via **phpmyadmin**. Example, I have two menu items: **A** and **B**

A => template_style_id = 0
It's correct because the default template style id will assign to this menu item.

Screenshot: https://imgur.com/q4Gjns6

B => template_style_id = 30
It's not correct because the default template style id is 0 (mean default template we assigned via template style) => caused error message:  **Default Layout file is not exists! Please goto to template manager and create a new layout first**

Screenshot: https://imgur.com/2ykHvPb

Explain: I don't know why but I seems I have assigned this menu item (B in this case) to special template style before, so when I uninstalled that template, the issue caused by Helix Ultimate 2.

Solution: Just open Menu item B and click SAVE to correct the template_style_id. The Menu item B in this case already set to Use default (template style) but it seems the template style id via database didn't update the value correctly. So we need to open and save to update it.

Screenshot: https://imgur.com/a/IajKeIE

Suggestion: I didn't get the issue with default Joomla template or Helix Ultimate 1, so in this case, we can add an exception for menu items that not listed from existing template style id by assigning the Default Layout to them. By this case we can avoid the issue with Default Layout file is not exists.

"Or could you please share how to reproduce the issue,so that we can identify the issue."
Sure, you can open phpmyadmin then assign a custom value for the template_style_id for special menu item to check :)

Thank you
