### ISSUE TITLE
Joomla 4 menu, menu item, link type, link image error

### ISSUE THREAD

**Issue by homeza-freeart** [JoomShaper/helix-ultimate#216]
If I want to add an icon to the menu item,
the website is completely falling apart.

Error message: 

Error: 0 Cannot access protected property Joomla\CMS\Menu\MenuItems::$params

**Comment by ahamed** [comment]
Could you please share more information? We have to recreate the situation. BTW, thanks for your issue.

**Comment by homeza-freeart** [comment]
So as I wrote earlier, I want an icon for a menu item. This is possible without any problems, but not for Joomla 4.
Current test environment:
Joomla 4.0.2
Helix Ultimate 2.0.1
Page builder pro 3.7.13

![ScreenShot_20210825180311](https://user-images.githubusercontent.com/82601395/130827197-6aff0f66-f954-410c-9f7a-23f5d7ff3141.png)
![ScreenShot_20210825180215](https://user-images.githubusercontent.com/82601395/130827244-d4c03318-5f40-4c71-85c5-1fe3d038cbe1.png)
![ScreenShot_20210825180504](https://user-images.githubusercontent.com/82601395/130827285-0a5a46a3-78c9-468c-abb3-6413cca30a25.png)

Attached 3 screenshots,
Admin (edit menu item)
Disintegrated site
Correct site
