### ISSUE TITLE
.burger-icon color settings

### ISSUE THREAD

**Issue by Rakeshmvd** [JoomShaper/helix-ultimate#217]
At the
Template Settings>Presets>Custom Style>Top Bar
Please add the settings for the .burger-icon color

It is very logical to add this setting so I do not need to add the custom css .burger-icon>span {background-color: #}

Thanks

**Comment by ssnobben** [comment]
Thanks agree pls fix this asap bcs as now the "hamburger" dissappear and difficult to customise

**Comment by mi-prakash** [comment]
This feature will come in the next update. so please wait for the helix ultimate update 2.0.12
closing the issue. if any problem arise please create a new issue
