### ISSUE TITLE
Font Awesome Icons for menus dissappear and also MegaMenu in backend

### ISSUE THREAD

**Issue by ssnobben** [JoomShaper/helix-ultimate#219]
### Steps to reproduce the issue
Upgrade from previous Helix Ultimate 1.4.1 to HU 2.0.1 - clean teamplate

### Expected result
Everything works and mega menu in HU works in backend to create mega menus and frontend with setting the Font Awesome Icons for menus work.

### Actual result
There is no MegaMenu for Helix Ultimate 2.0.1, it dissappear and there is no Font Awesome Icons to load for menus

### System information (as much as possible)
Joomla 3.10.1 Helix Ultimate 2.0.1 SP Pagebuilder Pro 3.7.13

**Comment by ChrisWST** [comment]
Hello! This is true, they don't work in the Joomla menu anymore, you can create megamenu and also add icons for menus in the Helix options: https://prnt.sc/1qn7a6y

**Comment by ahamed** [comment]
Hello @ssnobben,
As @ChrisWST said, we've moved the megamenu from menu settings to template settings. And I believe the `Font Awesome` option is disabled on your site. For enabling it, go to `Advanced > Font Settings > Enable Font Awesome`

**Comment by ssnobben** [comment]
Ok I reverted back to Helix 1.1.4 and then update again today to Helix Ultimate 2.0.2

But when I tried to go to Helix Ultimate template I got this error. administrator/index.php?option=com_ajax&helix=ultimate&id=37

An error has occurred.

    0 Attempt to assign property "preset1" on null 

Return to Control Panel

Never ending story to update and use Helix Ultimate :(

**Comment by ssnobben** [comment]
Well I uninstall everythin with the template and start all over again..I think thats the fastest solution forward here.

I see the hamburger icon dissappear and have some problem to customise too there

**Comment by mi-prakash** [comment]
closing the issue. if any problem arise please create a new issue
