### ISSUE TITLE
JVERION - constant name false

### ISSUE THREAD

**Issue by Demel75** [JoomShaper/helix-ultimate#222]
### Steps to reproduce the issue
Update to 2.0.2

### Expected result

Show Page

### Actual result

ERROR: Undefined constant "JVERION"

### Additional comments
edit plugins/system/helixultimate/overrides/com_content/featured/default_item.php and change JVERION to JVERSION

**Comment by ahamed** [comment]
Thanks for your issue. This will be fixed in the next version.
