### ISSUE TITLE
Edit Preset: New preset fields are not existing

### ISSUE THREAD

**Issue by tonamphong** [JoomShaper/helix-ultimate#224]
### Steps to reproduce the issue
Adding new field for Pre-defined Presets, like preset 1, e.g: Adding new **topbar_link_color** field. Its working for custom style but not working for pre-defined presets. 

### Expected result

The new preset field should appear when editing the preset data like we did with custom style

### Actual result
Not exist.  The form defined via root/plugins/system/helixultimate/src/form/preset.xml
Is it possible to override/modify the value via options.xml ?

### System information (as much as possible)
Latest Joomla 4 / Helix Ultimate

**Comment by ahamed** [comment]
Nope it's not possible. We've defined a rule for the presets. You should bound to the rule :)
