### ISSUE TITLE
scss responsive.scss dropdown menu width 

### ISSUE THREAD

**Issue by homeza-freeart** [JoomShaper/helix-ultimate#225]
A small but annoying css problem:
The shaper_helixultimate / scss folder contains a responsive.scss.
First of all:
@media (max-width: 1440px) {
.sp-dropdown.sp-dropdown-mega {
width: 920px! important;
}
}
This does not allow you to adjust the width of the dropdown menu in HU template settings.
Even if I set a width of 230px there, for example, scss will overwrite it.
(I don't even understand this 920px! Important; width) :) 
Why is it there?

**Comment by vandersell** [comment]
I can confirm this issue.
HU 2.0 Documentation says:  _"**Dropdown Width** -  Width value is used to declare submenu width content area. By default is 240px. ..."_ 

**Steps to reproduce the issue**
Menu Builder > Mega Menu : On > Menu Width : (empty) > Save
The Menu Width automatically becomes value 255px

**Expected result**
Dropdown is 255px wide

**Actual result**
Dropdown is 920px wide.
On screens from 1440px and larger, dropdown is 255px wide.
