### ISSUE TITLE
Quickstart Pack - Joomla 4 (Version 2.0.4) Left/Right Menu and favicon

### ISSUE THREAD

**Issue by dgjoom** [JoomShaper/helix-ultimate#228]
As I know the Menu Left and Right should be Vertical, as same with Joomla 3.
Just doing test at local host with the Quickstart pack Joomla 4 Version 2.0.4, the Left / Right menu become Horisontal.
Also the favicon look not visible.

Thanks

**Comment by ittoufiq** [comment]
If you have any menu module published, then please disable the menu module from the module manager. Check again and let us know. Thanks

**Comment by mi-prakash** [comment]
closing the issue as there is no feedback. Please re-create issue if any arises
