### ISSUE TITLE
New created positions is not showing in latest Joomla 4 Version

### ISSUE THREAD

**Issue by uzielweb** [JoomShaper/helix-ultimate#229]
### Steps to reproduce the issue

Create a new position, publish a module  in it

### Expected result

It's expected to view this module in that recently created position

### Actual result
The positions is not showing and the ?tpl=1 revela that nothing exists.

### System information (as much as possible)
Joomla 4 Helix Ultimate 2.0.4

**Comment by mdamjadrana** [comment]
can you share a scenario or example. this issue happend for helix are you sure?

**Comment by mi-prakash** [comment]
closing the issue as there is no user feedback. please create a new issue if any issue arise in further
