### ISSUE TITLE
Quick leap into Helix-Ultimate from Helix 3 with your help

### ISSUE THREAD

**Issue by fuzmic2** [JoomShaper/helix-ultimate#231]
Due to Joomla 4 arrival and Helix 3 not ready yet I decided to learn to use Ultimate with Jm4.  Hence i hope to get some help here fast instead of going for a general sweep in the website.

I just **found what i want**, changing row properties > style:  to change background color, padding, text colour.   So my conclustion now is we easily get started to use HX-Ultimate if you are familar with Helix 3, just a matter of looking around to get use to the new environment.

**Comment by mi-prakash** [comment]
There are lots of blogs related to helix ultimate, please go through them
https://www.joomshaper.com/blog/helix-framework
