### ISSUE TITLE
JHtml::_('bootstrap.popover', '.hasPopover'); JHtml::_('bootstrap.tooltip', '.hasTooltip'); not work in joomla 3

### ISSUE THREAD

**Issue by minijoomla** [JoomShaper/helix-ultimate#232]
### Steps to reproduce the issue
I used JHtml::_('bootstrap.popover', '.hasPopover'); and JHtml::_('bootstrap.tooltip', '.hasTooltip'); in a module .

### Expected result

tooltip and popover must show

### Actual result

tooltip and popover not work

### System information (as much as possible)

joomla 3.10.1

### Additional comments

tooltip and popover and other bootstrap functions are diffrent in bootstrap v5 and v2
i think you did not do any changes about these functions

**Comment by activha** [comment]
Same issue still not fixed as of January 2022
This breaks a lot of extensions for joomla 3. For instance render field for drop down lists does not work on Helix 2.0.6
Pretty urgent to find a fix
