### ISSUE TITLE
Justify content end  rule is used in header menu

### ISSUE THREAD

**Issue by 01Kuzma** [JoomShaper/helix-ultimate#236]
Helix Ultimate 2.0.x
Not predefined header is used

Custom layout:
![image](https://user-images.githubusercontent.com/569504/133773604-894ef097-1443-434f-9023-2beb44864202.png)

The middle element, where menu is placed uses `justify-content-end` rule! The menu is moved to the right position!
That's not good. It should be centred or there should be a possibility to set the desired alignment.
![image](https://user-images.githubusercontent.com/569504/133774106-2c57a16f-958a-4cfc-9263-bd1815a1c715.png)

**Comment by prakash-a7x** [comment]
@01Kuzma 
The template's default style is 'justify-content-end'.
If you want the menu in centre, there are many predefined header. Please choose from those
Hope this helps your problem
