### ISSUE TITLE
[2.0.5] Social Icons Custom fontawesome icon fa-map-marker dont work

### ISSUE THREAD

**Issue by brianeg** [JoomShaper/helix-ultimate#239]
### Steps to reproduce the issue
fa-map-marker https://www.google.dk/maps/dir//2100+København+ØCopenhagen/@55.7097071,12.5068258,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x4652532cd84a4c41:0x305bad6538f963f4!2m2!1d12.5768655!2d55.7096303

### Expected result
Icon for map-marker

### Actual result

![fa-map-marker](https://user-images.githubusercontent.com/25778395/134055523-d439fe00-a8e3-45a3-b2fc-4d83424ac47b.jpg)

### System information (as much as possible)
SP Page Builder Lite Version: 3.2.9
Helix Ultimate 2.0.5 og Joomla 3.10.2

### Additional comments
![code](https://user-images.githubusercontent.com/25778395/134226680-e23ba88f-c7da-44e0-8988-b32f6e68fa1f.jpg)

**Comment by brianeg** [comment]
old
<span class="fa fa-map-marker" aria-hidden="true"></span>

new
<span class="fab fa-map-marker" aria-hidden="true"></span>

It's ok here
<span class="fab fa-facebook" aria-hidden="true"></span>

**Comment by ahamed** [comment]
From the next version you can use your own icon prefix like `fas fa-map-marker`.
Thanks for your issue.
