### ISSUE TITLE
Preset color order on css compression mode.

### ISSUE THREAD

**Issue by tonamphong** [JoomShaper/helix-ultimate#240]
### Steps to reproduce the issue
Theme settings -> Advanced -> Compression -> enable Css compression

### Expected result

![correct](https://user-images.githubusercontent.com/2299347/135718058-3b5836d7-ac23-4494-b249-78b6445f4f01.png)

### Actual result

![in-correct](https://user-images.githubusercontent.com/2299347/135718074-b41d5de7-ca56-4f1c-8885-92e13cc149bd.png)

### System information (as much as possible)
J4!/Helix/Shaper 2.0.5

### Additional comments
The preset.css file should be added to the last order to avoid the color override from template/bootstrap css files.

**Comment by spro11** [comment]
I confirm. There really is a problem. For this reason, css file compression cannot be used.
