### ISSUE TITLE
Mega menu - don`t work

### ISSUE THREAD

**Issue by LGMaxim** [JoomShaper/helix-ultimate#241]
### Steps to reproduce the issue
The mega menu tab is not displayed in the Joomla menu settings
The selection of the module for the mega menu in the template settings does not work for Russian language

![image](https://user-images.githubusercontent.com/91878193/135826681-44f46516-0e1e-4274-893e-e27488006196.png)
![image](https://user-images.githubusercontent.com/91878193/135827290-4e341f50-1f66-4150-b19c-596924473113.png)

### System information (as much as possible)
Joomla 3.10.2
Helix 2.0.5

**Comment by prakash-a7x** [comment]
Tested it, everything is working fine in both j3 and j4.
Closing this issue
