### ISSUE TITLE
Joomla 4 Error in Helix Ultimate: 500 behavior::modal not found error,

### ISSUE THREAD

**Issue by trainspotting** [JoomShaper/helix-ultimate#242]
500 behavior::modal not found error.

Third party component maker told me to report this to you. Saying:

Caused by the override made for user form field
JROOT/plugins/system/helixultimate/overrides/layouts/joomla/form/field/user.php:52 . 
It is using a method which was removed in Joomla 4

![error2](https://user-images.githubusercontent.com/13025180/135844997-6a1aff83-da11-412e-a704-67d545f20832.png)

**Comment by mdamjadrana** [comment]
can you share component name?

**Comment by trainspotting** [comment]
Hi. Yes Membership Pro from JoomDonation

**Comment by prakash-a7x** [comment]
@trainspotting 
Are you still facing this issue with the latest 2.0.9 update?
Please let us know, there was a fix for this issue.
