### ISSUE TITLE
bug on Off Canvas menu when installed on Joomla 4

### ISSUE THREAD

**Issue by aminweb2** [JoomShaper/helix-ultimate#245]
### Steps to reproduce the issue
Website1 ==> installed Joomla 3.10 + installed Helixultimate 2.0.5
Website2 ==> installed Joomla 4.0.4 + installed Helixultimate 2.0.5

### Actual result

Website1 Off Canvas menu tested by ::
A) iphone 8 and Samsung ==> Worked
B) ipad 4 ios 10 ==> Worked

**Website2** Off Canvas menu tested by ::
A) iphone 8 and Samsung ==> Worked
B) **ipad 4 ios 10** ==> **NOT WORKED**

### Result

Helixultimate 2.0.5 have bug on Off Canvas menu when installed on Joomla 4 (when test by ipad 4 device)

**Comment by mdamjadrana** [comment]
what kind of bug please share in details. with some screenshoot.

**Comment by ittoufiq** [comment]
Also, I have checked my end and no problem was found.
