### ISSUE TITLE
Conflict Between Helix Ultimate 2.0.6 And Popup With Jce Mediabox

### ISSUE THREAD

**Issue by gioacchino54** [JoomShaper/helix-ultimate#248]
### Steps to reproduce the issue

[https://www.loom.com/share/e1c4a218976840968bc2640863f26fd7](url)

### Expected result
[https://www.loom.com/share/e1c4a218976840968bc2640863f26fd7](url)

### System information (as much as possible)
Joomla! 3.10.3
Php 7.4.x
Helix Ultimate 2.06

### Additional comments
I am configuring, on a local server, a pop through JCE Mediabox. It used to work, now with HU 2.0.6, it doesn't work anymore. To show what I mean I used the Protostar template. You can see the behavior in the video, alternating templates (Helix Ultimate and Protostar) you can see the wrong behavior.

**Comment by glinneberg** [comment]
I have the same issue. Popups worked fine until 2.0.36. I took the issue to JCE and they hadn't changed anything. They did have a look at one of my pages where the popup wouldn't load and sent me this:

![jce](https://user-images.githubusercontent.com/96304026/146568958-f3bdc5f1-1683-419f-b787-4b1df6d3943e.jpg)

**Comment by gioacchino54** [comment]
> I have the same issue. Popups worked fine until 2.0.6. I took the issue to JCE and they hadn't changed anything. They did have a look at one of my pages where the popup wouldn't load and sent me this:
> 
> ![jce](https://user-images.githubusercontent.com/96304026/146568958-f3bdc5f1-1683-419f-b787-4b1df6d3943e.jpg)

We hope that Joomshaper will find a solution soon

**Comment by glinneberg** [comment]
Yes, I'm really hoping this can get resolved. I miss those popups.

**Comment by gioacchino54** [comment]
I changed the two files as an indicator in the solution: https://github.com/JoomShaper/helix-ultimate/commit/bfab89724112cd9a37c8e7d36323a41370576729
But the result hasn't changed the JCE Popup remains to not work.
Best Rgds
Gioacchino
