### ISSUE TITLE
[2.0.6] Featured MenuItem type - No columns - More Items display inline

### ISSUE THREAD

**Issue by pepperstreet** [JoomShaper/helix-ultimate#249]
### Steps to reproduce the issue

- Create a MenuItem of type > Articles > **Featured Articles** 
- Set amount of **Columns** to 2 or more.
- Set amount of **Links** to 2 or more.

### Expected result
- 2 or multi-column Blog display.
- More Items should appear as a vertical, styled, un-ordered list. (UL/LI with respective [Bootstrap5 classes](https://getbootstrap.com/docs/5.1/components/list-group/) like _list-group_ or _list-group-flush_)

### Actual result
- No columns. All items are stacked vertically.
- "More Items" links appear horizontal as un-styled ordered list (OL/LI)

### System information (as much as possible)
Joomla 3.10.x
Joomla 4.0.4
Helix Ultimate 2.0.6

### Additional comments
In Joomla 3.10.x the columns work!
Only the "More Items" links are inline and horizontal. _links sublayout misses Bootstrap classes.

**Comment by coufalpetr** [comment]
I confirm the error (there is a problem with the calculation of columns in the code).

**Comment by matrix630307** [comment]
does anyone have a manual solution until this bug is fixed?

**Comment by matrix630307** [comment]
No one with an idea to this great bug?

**Comment by aranemac** [comment]
I can confirm this for joomla 4

My workaround was, to create an override and patch the code:
In
templates/shaper_helixultimate/overrides
I created a subfolder
com_content/featured
and copied default.php from
plugins/system/helixultimate/overrides/com_content/featured
into it
(So it will not be overwritten by template-updates)

In default.php I changed
        $this->columns = $this->columns ?? 1;
to
        $this->columns = $this->columns ?? 3;
(I want three columns)

Of course it is only an individual dirty patch, but it works for me

**Comment by matrix630307** [comment]
hi aranemac
super! i will try this.
thank you very much for this solution!
wish a merry christmas

**Comment by aranemac** [comment]
And after I looked into the Joomla 4 core file, I finally changed it to:

$this->columns = $this->columns ?? ( $this->params->get('num_columns') ?? 1 );

This should be a real fix, which reads the values from the menu-settings.
(But I did not test it with additional leading articles)

Merry chrismas to you too

**Comment by matrix630307** [comment]
hi achim
ok - i have try your solution and it work's fine!
i will wait to joomlashack that will made a bugfix - so i hope - for this.
when i made this in core file, then it will override by an update from helix.
your solution is great!
many thank's

**Comment by pepperstreet** [comment]
> when i made this in core file, then it will override by an update from helix.
As mentioned above, your changes will be save on updates, since HU2 invented another override method. Put your fixed/patched files here: 
_YourJoomla/templates/shaper_helixultimate/overrides/.._

**Comment by pepperstreet** [comment]
Thanks for fixing the featured COLUMNS issue. But you have missed the **LINKS sub layout**. _More articles_ are still missing the respective Bootstrap5 classes and styling... Probably I should have opened a separate issue!? I am going to create a new, separate one for HELIX v2.0.7 ;)
