### ISSUE TITLE
Sticky logo not loading

### ISSUE THREAD

**Issue by nzimas** [JoomShaper/helix-ultimate#250]
### Steps to reproduce the issue

1. Assign one image to the Logo field (Basic > Logo)
2. Assign another image to the HELIX_ULTIMATE_LOGO_STICKY field (Basic > Logo)

### Expected result

When the website loads, the image assigned to the Logo field should load.

When the user scrolls down into the content area, the image assigned to the HELIX_ULTIMATE_LOGO_STICKY field should load (inside the sticky header).

### Actual result

The image assigned to the Logo field loads in the sticky header.

### System information (as much as possible)

Joomla! 3.10.3
Helix Ultimate 2.0.6
PHP 7.3.s

### Additional comments

This bug report is based on the assumption that the HELIX_ULTIMATE_LOGO_STICKY filed is used to load the website logo inside the sticky header once the user starts scrolling down.

Screenshots:

<img width="408" alt="Screenshot 2021-12-13 at 13 13 15" src="https://user-images.githubusercontent.com/6955694/145802491-94423793-15d3-4fcd-9a43-967e4ea69b4d.png">
<img width="393" alt="Screenshot 2021-12-13 at 13 12 59" src="https://user-images.githubusercontent.com/6955694/145802502-2767ebd9-cc1a-4b7c-a001-a7083804b67c.png">

**Comment by mdamjadrana** [comment]
It's template related issue. please share your template name. Please do a post on our support forums.
https://www.joomshaper.com/forum
