### ISSUE TITLE
Frontend editing error "0 Call to a member function format() on bool" on save when using date format other than default setting of en-GB content language

### ISSUE THREAD

**Issue by EvDoorne** [JoomShaper/helix-ultimate#251]
### Steps to reproduce the issue

- Set content language to a language that uses a date format different from en-GB, for instance nl-NL.
- Setup a menu item to create a new article via frontend-editing.
- Start the creaton of a new article via the menu item.
- SET the publishing date to a date (do not leave blank). Any date value will do.
- Save the article.

### Expected result

- Article will be saved, pulbishing date will be current date + time

### Actual result

- A error "0   Call to a member function format() on bool" is generated,
- The article is not saved.

### System information (as much as possible)
- J! 4.0.5
- Helix Ultimate 2.0.5
- Ubuntu 20.04 LTS

### Additional comments

- Leaving the publishing date empty will make it possible to save the article, but the stored publishing date is wrong when the article is opened again for editing.
- Setting the content language back to a language that has the same default date format as en-GB will make the error go away.
- This appears independant of the editor selected as default editor.

**Comment by EvDoorne** [comment]
I would like to add that reverting to the Cassiopeia template resolves the issue. It's defilitely related to Helix Ultimate.

**Comment by 4ndyZ** [comment]
I have the same problem with another language package. I am using de-DE.

### Steps to reproduce the issue

Same as op, but the issue happens when I change it from en-GB to de-DE

### Expected result

Same as op

### Actual result

Same as op

###  System information (as much as possible)
 
Joomla! 4.0.5 Stable [ Furaha ] 11-December-2021 20:52 GMT 
Helix Ultimate 2.0.5
Webserver Apache
PHP Version 8.0.13

**Comment by 4ndyZ** [comment]
The following issue in Joomla Core is related to this problem.

[https://github.com/joomla/joomla-cms/issues/36150](Joomla CMS #36150)

**Comment by 4ndyZ** [comment]
@mdamjadrana

The problem still exists in the latest version if Helix Ultimate (2.0.6) and did not get fixed.

The publishing date is also wrong (first sscreenshot frontend and the second one of the backend).
![image](https://user-images.githubusercontent.com/54391621/152793713-db5d574c-6edf-4830-be47-78b9f6d36dcd.png)

![image](https://user-images.githubusercontent.com/54391621/152794134-b698fa86-9a05-4cd9-aba5-3ab6d8d2ae95.png)

I guess there still is a format error in the date parsing process.

### 
System information

Joomla! 4.0.6 Stable
Helix Ultimate 2.0.6
Webserver Apache

**Comment by 4ndyZ** [comment]
Same problem with the latest version of Joomla und Helix Ultimate.

### System information

Joomla! 4.1.0 Stable
Helix Ultimate 2.0.7
Webserver Apache
