### ISSUE TITLE
Bootstrap.tooltip problem

### ISSUE THREAD

**Issue by ErikMalfait** [JoomShaper/helix-ultimate#252]
I updated the Helix Ultimate template on my site today and now my EventBooking Full Calendar is no longer showing.
When I switch to a different template, it is still working fine.

This is the feedback I got from EventBooking support:

I think you should report this issue to Helix developer. Calling the below Joomala core code:

HTMLHelper::_('bootstrap.tooltip');

causes some javascript error with their template (note that it is a Joomla core command to load bootstrap tooltip):

Uncaught TypeError: $(...).find(...).tooltip is not a function
at initTooltips (agenda:50)
at HTMLDocument. (agenda:50)
at u (jquery.min.js?936c3888469cf292a9a9f68e6ae2e689:2)
at Object.fireWith [as resolveWith] (jquery.min.js?936c3888469cf292a9a9f68e6ae2e689:2)
at Function.ready (jquery.min.js?936c3888469cf292a9a9f68e6ae2e689:2)
at HTMLDocument._ (jquery.min.js?936c3888469cf292a9a9f68e6ae2e689:2)

They should check to see why the issue happens and get it sorted. Otherwise, there would be issues with many extensions use that Joomla core code

For now, I commented out that line of code in Events Booking, the javascript error is gone and calendar is being displayed now

**Comment by mdamjadrana** [comment]
Did you updated you main.js tooltip code with latest bootstrap upgrade.

Here is the latest update.
```
// Tooltip
	var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"], .hasTooltip'));
	var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
		return new bootstrap.Tooltip(tooltipTriggerEl,{
			html: true
		  });
	});
```
