### ISSUE TITLE
Joomla Intro and Full Image path issues

### ISSUE THREAD

**Issue by MayaSima** [JoomShaper/helix-ultimate#261]
### Steps to reproduce the issue
Create a new Joomla article and select or upload an intro or full image (as an example we use powered_by.png) in the Images and Links section.

### Expected result
`<img src="/images/powered_by.png" alt="" itemprop="thumbnail" width="294" height="44" loading="lazy">`

### Actual result
`<img src="/images/powered_by.png#joomlaImage://local-images/powered_by.png?width=294&amp;height=44" alt itemprop="image">`

### System information (as much as possible)
Helix Ultimate 2.0.7
Joomla 4.1.0
MySQL 8.0.28
PHP Version 8.0.16

**Comment by prakash-a7x** [comment]
@MayaSima 
Noted the issue, we will hopefully fix it in the next update.
Thank you for your patience
