### ISSUE TITLE
Module - Problem of appearance in the assigned position

### ISSUE THREAD

**Issue by Robx91** [JoomShaper/helix-ultimate#264]
### Steps to reproduce the issue
Assign joomla 4 Module Feed Generator in Top1 position in default template and a copy of it.

### Expected result

the result should be that the module appears in the assigned pages both in the default template and in its copy ...

### Actual result

The module appears in the pages managed by the copy while in the pages of the default template there is nothing.

### System information (as much as possible)

joomla 4.0.6 helix Ultimate 2.0.7 (but also 2.0.6 or 2.0.5)

### Additional comments
The pages of site are assigned correctly ... the cache cleared several times both from the site and from the browser ... nothing ... I do not go out ...

**Comment by prakash-a7x** [comment]
@Robx91 
I've tried to reproduce the issue, I think everything is working fine, you need to assign the position of the module to the helix layout properly.
Please follow the attached video. 
If this doesn't solve your issue please make a video and attach it here to understand the problem properly.

https://user-images.githubusercontent.com/42798816/162169512-42ee840c-6e81-4c74-abb5-014200b82035.mp4
