### ISSUE TITLE
Problem with media fields and media preview

### ISSUE THREAD

**Issue by chattigre** [JoomShaper/helix-ultimate#266]
### Steps to reproduce the issue
Use "Images and links" creation tab in frontend.
OR Use a custom field of type "media"
Select a media / change a media 

### Expected result
No problem with Cassiopeia template : Media preview, no console errors.

### Actual result
On pageload, I have the following error message in my browser console : `Uncaught TypeError: Joomla.initialiseModal is not a function`
`connectedCallback joomla-field-media.min.js:121
    <anonymous> joomla-field-media.min.js:235`
The media preview doesn't work on media selection / change, you get an alert : _Internal server error_

### System information (as much as possible)
Joomla 4.1
PHP 7.4
Helix Ultimate 2 latest version

### Additional comments

If I delete the file bootstrap.bundle.min.js which is in the js template's folder, the problem disappears... But I think that this Javascript file is necessary, so it looks to be a scripting conflict.

Seems maybe linked to issue #261 

**Probable source :** #258

**Comment by joomleb** [comment]
Hi guys, 
I seems the same problem as:
#243 
#258 
#285

**Comment by mi-prakash** [comment]
@joomleb 
We believe this issue has been resolved and closed. Please use the latest helix version
thank you
