### ISSUE TITLE
All following checkboxes are disabled as soon as one checkbox is disabled

### ISSUE THREAD

**Issue by HSorgYves** [JoomShaper/helix-ultimate#267]
### Steps to reproduce the issue
Create a checkboxes field with three checkboxes in a form. Set the second checkbox to disabled.

### Expected result
Only disable the second checkbox. The third checkbox should not be disabled.

### Actual result
The second and the third checkbox are disabled.

### System information (as much as possible)
Joomla! ver. 4.1.2
Helix Ultimate ver. 2.0.7

### Additional comments
The problem is the line 69 in ./plugins/system/helixultimate/overrides/layouts/joomla/form/field/checkboxes.php
`$disabled    = !empty($option->disable) || $disabled ? 'disabled' : '';`

The bug has been fixed in Joomla! in line 74 of ./layouts/joomla/form/field/checkboxes.php
`$optionDisabled = !empty($option->disable) || $disabled ? 'disabled' : '';`

P.S.: You need to change $disabled to $optionDisabled in line 77 too.
`$attributes = array_filter(array($checked, $optionClass, $disabled, $onchange, $onclick));`

**Comment by prakash-a7x** [comment]
@HSorgYves

**Comment by prakash-a7x** [comment]
@HSorgYves 
Noted the issue, We will fix the issue in future updates. 
Thanks
