### ISSUE TITLE
Gallery Carousel slide bug (since HU 2.0 to 2.07)

### ISSUE THREAD

**Issue by Savama51** [JoomShaper/helix-ultimate#269]
### Steps to reproduce the issue

Install fresh Joomla! 3 or 4, and latest Shaper_helixUltimate with a blog category visible in frontend.
Create an article in this blog category with more than one picture in the article format "Gallery".

Or :

Go to the following JoomShaper's Helix Ultimate demo page :
https://demo.joomshaper.com/2018/helixultimate/index.php/blog/want-to-make-more-baskets-science-has-the-answer

### Expected result

The gallery carousel start to slide after page loading.

### Actual result

The gallery carousel doesn't start to slide.
You have to click prev or next carousel button to start the slide.

### System information (as much as possible)

Joomla 3.x or 4.x
Shaper-HelixUltimate 2.0 to 2.0.7

### Additional comments

Way to fix it :

1. Copy `plugins\system\helixultimate\overrides\layouts\joomla\content\blog\gallery.php` override file to `templates\shaper_helixultimate\overrides\layouts\joomla\content\blog\gallery.php`
2. Edit the file.
3. Line 20: modify `data-ride="carousel"` to `data-bs-ride="carousel"`

**Comment by prakash-a7x** [comment]
@Savama51

**Comment by prakash-a7x** [comment]
@Savama51

**Comment by prakash-a7x** [comment]
@Savama51 
I've checked and found the issue.
Hopefully it will be fixed in the next update.
Thank you for your patience

**Comment by Savama51** [comment]
> @Savama51 I've checked and found the issue. Hopefully it will be fixed in the next update. Thank you for your patience

I hope these fixes! Despite these little bugs, HU is a great tool !

**Comment by Savama51** [comment]
HU 2.08 resolves it !
