### ISSUE TITLE
Alert box close button (J3)

### ISSUE THREAD

**Issue by Savama51** [JoomShaper/helix-ultimate#270]
### Steps to reproduce the issue

Install fresh Joomla! 3, and latest Shaper_helixUltimate.
Create a contact form.
Go to frontend, in the contact form page.

Or :

Go to the following JoomShaper's Helix Ultimate demo page :
https://demo.joomshaper.com/2018/helixultimate/index.php/pages/contact

Leave the form fields blank and click on "send" button.
A pale red alert box appears at bottom right

Click the alert box close button.

### Expected result

Clicking the close button should close the alert box.

### Actual result

Clicking the close button does nothing.

### System information (as much as possible)

Joomla 3.x
Shaper-HelixUltimate 2.0.7

### Additional comments

It seems that this bug only affect J3, not J4.
So we could think that the Helix Ultimate demo site is still based on Joomla 3 core, not 4... ^^

Way to temporarily fix it (not clean, but it works!) :
1. Edit file `templates\helixultimate\js\bootstrap.bundle.min.js`
2. Line 6, col 7091, replace `data-bs-dismiss` by `data-dismiss`

**Comment by Savama51** [comment]
Oops... duplicate with Issue #246... Sorry !

But no response since february about this real bug ;)

**Comment by prakash-a7x** [comment]
@Savama51 
Tested and found the issue. It will be fixed on next update.
Thank you for your patience.

**Comment by Savama51** [comment]
HU 2.0.8 resolves it !
