### ISSUE TITLE
Article show message "expired"

### ISSUE THREAD

**Issue by matrix630307** [JoomShaper/helix-ultimate#276]
### Steps to reproduce the issue
I have installed "Helix Ultimate Template" v 2.0.7 and "System - Helix Ultimate Framework" 2.0.7 for any time. All work's fine. Then i updated to Version 2.0.8. In this case, the message "expired" will show in Articles, they have a expired date in the future.

### Expected result
No show the expired message.

### Actual result
Show expired message in Articles

### System information (as much as possible)
Joomla 4.1.2, Helix Ultimate 2.0.8 and Framework 2.0.8

### Additional comments
When i deinstall the versin 2.0.8 completely - install the Template 2.0.7 and Framework 2.0.5, then the message will not show. Then update only the framework to 2.0.8, the message "expired" will show.

**Comment by matrix630307** [comment]
Great!!! Many Thanks for your Work!

**Comment by prakash-a7x** [comment]
@matrix630307 
Your most welcome
