### ISSUE TITLE
joomla-alert notification below bootstrap cards

### ISSUE THREAD

**Issue by alfredojdd** [JoomShaper/helix-ultimate#278]
Hi, excuse my english.
Maybe could be a problem generated by me, but I did not notice it until the last Joomla Update....
### Steps to reproduce the issue
With the latest Joomla update, I have noticed that the notifications generated by Helix are placed below the bootstrap cards so they become invisible and do not close automatically.
### Expected result
![captura 1](https://user-images.githubusercontent.com/17855375/171435475-e0f316dd-d943-4830-86aa-70bf64b1f2f9.png)
The alert is above the page content (a table). In this case, it is visible but does not close automatically, must be closed with the X button.
### Actual result
![captura 2](https://user-images.githubusercontent.com/17855375/171436071-50d16bd2-3599-4144-9bf4-6c6cba915abe.png)
The first alert is hidden below the card, the second is partially visible. None of them closes automatically.
### System information (as much as possible)
Joomla 4.1.3 updated to 4.1.4
Helix 2.0.8 updated to 2.0.9
### Additional comments
Thanks!!

**Comment by prakash-a7x** [comment]
@Savama51 thanks for your feed back
We will resolve this issue in the next update.
