### ISSUE TITLE
JInstaller: :Install: Can't find XML setup file.

### ISSUE THREAD

**Issue by raramuridesign** [JoomShaper/helix-ultimate#279]
### Steps to reproduce the issue
try an update from 
![image](https://user-images.githubusercontent.com/902376/172130890-97c9542e-5dc8-457a-9e46-bf117503ee2d.png)

### Expected result
The template does not update, results in the following error
`JInstaller: :Install: Can't find XML setup file.`

![image](https://user-images.githubusercontent.com/902376/172131109-17d799f4-aa50-42a6-b792-c9ef28729252.png)

### System information (as much as possible)
Joomla: 3.10.9
Helix template: 2.0.7
Helix System plugin: 2.0.9
PHP 7.4.x

### Additional comments
Have tried to do a manual update which results in the same error

**Comment by mi-prakash** [comment]
@raramuridesign 
are u still facing this problem with latest helix ultimate build and latest joomla?
please confirm otherwise we can close the issue

**Comment by raramuridesign** [comment]
At the moment, I have not encountered any issues, if I do, I will re-open. I am closing this, thanks for following up.
@mi-prakash

**Comment by mi-prakash** [comment]
@raramuridesign thanks for the feed back
