### ISSUE TITLE
After upgrading HU to j3 v2.0.9, there is an error with the sp page builder image add-on.

### ISSUE THREAD

**Issue by homeza-freeart** [JoomShaper/helix-ultimate#287]
After upgrading HU to j3 v2.0.9, there is a bug in the joomla article integration with the sp page builder image add-on!
In the frontend interface, the image addon open lightbox function still works well during editing,
but as soon as you leave, exit the frontend editor and update, the error will occur.

The open lightbox does not open modally, but appears with a simple browser window!
Very confusing!
What could be done with this?

(SPPB is also the latest version)

**Comment by prakash-a7x** [comment]
@homeza-freeart 
Please give us more informations. 
What does the error say? Give us screenshots or a video to understand properly.
What is your php version?
what is your Joomla version?

**Comment by homeza-freeart** [comment]
i made a video about the problem.
It appears that the modal window will no longer work when upgrading to HU 2.0.9.
link to video: https://freeart.hu/images/HU_modal_problem.mp4
(I cut it out of the video when I put back version 2.0.7.)
The problem is only in Joomla 3, not in Joomla 4.
SP Page Builder v3.8.7

**Comment by homeza-freeart** [comment]
I made a video about the problem.
(I cut out that the modal window in the image addon works again after replacing the previous version of HU.)

link to the video: https://freeart.hu/images/HU_modal_problem.mp4

The problem is only in Joomla 3, not in Joomla 4.
SP Page Builder v3.8.7

PHP 7.4.30
SP page builder version: 3.8.6 and 3.8.7

**Comment by homeza-freeart** [comment]
I was hoping that the above-mentioned error would change with the HU 2.0.10 update.
The thing is, IT HAS NOT CHANGED. The appearance of the image addon modal still works incorrectly!
Is anyone dealing with this problem or do I just have to live with it??

**Comment by prakash-a7x** [comment]
@homeza-freeart We have found and identified the issue. We will fix the issue in the next update.
Thank you for your patience and your valuable feedback

**Comment by homeza-freeart** [comment]
Thank you!
