### ISSUE TITLE
Issues with Smart Search on the latest version

### ISSUE THREAD

**Issue by ChrisWST** [JoomShaper/helix-ultimate#289]
Hello! 
I found an issue after latest helix plugin update with the com_finder from plugins\system\helixultimate\overrides on line 11, there's a fatal error.
I copied the com_finder folder from helix 2.0.9 and it works.

**Comment by Savama51** [comment]
Maybe because in the release 2.0.10's package, folder plugins\system\helixultimate\overrides\com_finder we find a "tmpl" folder instead of "search" folder !!

So, 2.0.10 resolves somes issues, but introduces new ones ...

**Comment by prakash-a7x** [comment]
@ChrisWST 
Are you facing this issue in Joomla 3 or 4 ?

**Comment by ChrisWST** [comment]
Joomla 4, but the issue is related to what @Savama51 said, you forgot to remove the tmpl folder.

**Comment by Savama51** [comment]
> [..] you forgot to remove the tmpl folder.

Not exactly, the "tmpl" folder **should be named** "search".

**Comment by prakash-a7x** [comment]
@ChrisWST 
Ok, we will note this
Just another question. Have you upgraded your Joomla from 3 to 4 or was is just a Joomla 4 from the start?

**Comment by ChrisWST** [comment]
@Savama51, the search folder is inside the tmpl folder, if you move it one level, the smart search works.

@prakash-a7x , It was Joomla 4 from the start, no upgrate.

**Comment by Savama51** [comment]
> @Savama51, the search folder is inside the tmpl folder, if you move it up one level, the smart search works.

You are right !

**Comment by prakash-a7x** [comment]
@Savama51 Thanks for your feedback, we will note the issue and try to fix this in future updates
Thank you for your patience

**Comment by Savama51** [comment]
Strangely, the latest 2.0.11 update doesn't solve this issue...

**Comment by joomleb** [comment]
Hi,
[Helix Ultimate 2.0.12](https://www.joomshaper.com/downloads/template/helixultimate) has been release with this fix included.

@ChrisWST  &  @Savama51 
Please, Can you confirm that is run as expected and that the ticket can be closed ?!?

**Comment by ChrisWST** [comment]
Hello,

Yes, the tmpl folder is gone and now it should work.
