### ISSUE TITLE
if click on option the off-canvas menu body display all the time 

### ISSUE THREAD

**Issue by sofianhit** [JoomShaper/helix-ultimate#290]
helix ultimate version 2.0.10
i am using just template not quickstart 
please see image and vedeos :
![canvas issue](https://user-images.githubusercontent.com/106688131/179325328-912f495a-62a4-42b3-9cfd-7b16637c024c.png)

https://user-images.githubusercontent.com/106688131/179325331-24b7f046-af38-4b1f-b546-472f97ae535f.mp4

https://user-images.githubusercontent.com/106688131/179325437-9082ce82-e79b-4229-b1c1-eab3b5ba43fe.mp4

there is no any way to hide it , it force me to uninstall the template and install it again .

**Comment by prakash-a7x** [comment]
@sofianhit 
I've tested with fresh Joomla 4 without the quickstart pack. Everything is working fine.
Can you give us more information like,
Whats ur PHP version and Joomla Version?
Please check my video

https://user-images.githubusercontent.com/42798816/180713504-07efadb3-8b03-4c3e-b11e-eb5213667802.mov

**Comment by mi-prakash** [comment]
Closing this issue as there is no feedback
