### ISSUE TITLE
Missing og:image when using Joomla Full Article Image

### ISSUE THREAD

**Issue by mojeweb** [JoomShaper/helix-ultimate#292]
### Steps to reproduce the issue
Create article with default Joomla Full Article Image.

### Expected result

Corect og:image <meta property="og:image" content="site.com/images/article-image.jpg" />

### Actual result
og missing

### System information (as much as possible)

HU 2.0.10 and Joomla 4.15

**Comment by mi-prakash** [comment]
@mojeweb 
This is the default joomla feature. Check with Cassiopeia template.
The same scenario occurs.

**Comment by mojeweb** [comment]
@mi-prakash 
Open graph is not Joomla feture. With Cassiopea there is NO open graph meta.
This is feature from HU. Joomla does not have open graph feature by default.
Quote from HU:
This option will add open graph content to the article so that social media like Facebook & Twitter can show correct image for the article. Disable this option if you want to use 3rd party open graph extension.

So problem is with HU open graph not supporting Joomla Full Article Image.

**Comment by mi-prakash** [comment]
@mojeweb 
Ok, we will investigate on this.
thanks for your comment
