### ISSUE TITLE
Blog Options, article format Gallery

### ISSUE THREAD

**Issue by mojeweb** [JoomShaper/helix-ultimate#294]
### Steps to reproduce the issue
Create article with Blog Options, article format Gallery and add some images with alt tag.

### Expected result

`<img src="/images/image.jpg" alt="alt text">
`
### Actual result

`<img src="/images/image.jpg" alt=" ">
`

### System information (as much as possible)

Joomla 4.15 and HU 2.0.10

**Comment by mi-prakash** [comment]
@mojeweb I've tested it and haven't found any issue like this. The alt tag is showing data just fine

**Comment by mojeweb** [comment]
![gallery-git](https://user-images.githubusercontent.com/45881772/183882903-27ada822-4c09-4d5c-89d3-ff01f83bd10b.jpg)

@mi-prakash  I have result like this.
Can you share live example?

**Comment by mi-prakash** [comment]
@mojeweb  yes
please check the video

https://user-images.githubusercontent.com/42798816/183888890-2ebd0f34-4db6-4949-b830-2d3faa812a20.mov

**Comment by mojeweb** [comment]
Create article with Blog Options, **article format Gallery**

You are using Standard.

**Comment by mi-prakash** [comment]
@mojeweb For now, there is no image alt text filed for Gallery. So you will not get any alt text there. 
In future update we might include this feature.
Thank you

**Comment by mojeweb** [comment]
Empty alt in my opinion is a bug or por development. So this is not a feture, but must.
Thank you
