### ISSUE TITLE
Full support of PHP 8?

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [JoomShaper/helix-ultimate#295]
### Is your feature request related to a problem? Please describe.
I am using latest helix ultimate template 2.0.10 and it does not work with PHP8 .

### Describe the solution you'd like
I would to see in the next release full support of PHP8

**Comment by EvDoorne** [comment]
Hallo,

ik heb momenteel een korte vakantie t/m 17 augustus. Ik lees mijn mail pas als ik weer terug ben van vakantie en zal dan ook op je bericht antwoorden.

Heb je een urgent probleem of verzoek, stuur dan een e-mail naar ***@***.*** Je e-mail wordt dan opgepikt door mijn collega's en je krijgt dan z.s.m. antwoord of er wordt contact met je opgenomen.

Dank je wel, hartelijke groeten van 

Erik van Doorne

**Comment by orlovskyjavaprofi** [comment]
I got the newest update and it works ! Cool! Support PHP 8.1 working!
