### ISSUE TITLE
DPCalendar doesn't work since v. 2.0.10

### ISSUE THREAD

**Issue by AlainRnet** [JoomShaper/helix-ultimate#297]
### Steps to reproduce the issue
1. Install J! v.4 with DPCalendar v.8.0.4 or v.8.0.5 and helix-ultimate v.2.0.10 or v.2.0.11
2. Create an event in DPCalendar component
3. Book this event
4. With admin login, modify the booking on frontend
5. After saving, you come back to the home page and you can an see error message on bottom right : Incorrect integer value: '' for column `_dpcalendar_bookings`.`user_id` at row 1

**Comment by mi-prakash** [comment]
@AlainRnet 
I tried to recreate this issue but so far haven't found any problem.
Can you give more detail. Sharing a video will help to understand the issue clearly
Thank you

**Comment by AlainRnet** [comment]
Thank you very much, but It's okay an d I wanted to post here today: DPCalendar developer gave me a patch yesterday. I think it will be part of the next release.
I never make a video from my screen. Do you have some easy Linux tools for that ?
However I have a test website and I can give you an access.

**Comment by mi-prakash** [comment]
@AlainRnet 
Sorry i don't use linux, but here is a useful link you can read
[https://itsfoss.com/best-linux-screen-recorders/](https://itsfoss.com/best-linux-screen-recorders/)
Is it working ok now with the patch? let us know. If everything is ok then we can close the issue.
And if you want us to test website please post it in our forum, it's safe there to give credential access.
[https://www.joomshaper.com/forum](https://www.joomshaper.com/forum)
Thank you

**Comment by AlainRnet** [comment]
Thank you very much !
