### ISSUE TITLE
[2.0.11 Bug] Header > Height: never applied

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#301]
Hi guys, 
PHP 7.4.33 + Joomla 3.10.11 + Helix Ultimate 2.0.11

Basic > Header > Predefined header: **Off**
Basic > Header > **Height**: 70px (for ex., I tested it with different values with the same result)
Basic > Header > Sticky header: On

The Height is never applied, it is always shown as 80px. It seems also that this CSS is causing a conflict:
#offcanvas-toggler {
  height: 80px;
  line-height: 80px;
}

VICE VERSA
Basic > Header > Predefined header: **On**
The height is always 56px and, again the Height I set is never applied...

Please, Can you confirm and fix it ?

**Comment by joomleb** [comment]
Really too strange... :
It was happen after an Helix Ultimate 1.1.4 > 2.0.11 upgrade.

I edited:
Layouts > Header > Style > Padding: ....
Saved

And the issue seems to be fixed....

**Comment by mi-prakash** [comment]
@joomleb 
Thanks for your feedback. It seems the issue occurred because of some backward compatibility.
Hope everything is working fine now. If there is no problem related to this issue then we can close this issue
Thank you

**Comment by joomleb** [comment]
@mi-prakash 
yes, I agree. Right now all is working fine.
In case of new related issue I'll be back here...

**Comment by mi-prakash** [comment]
@joomleb In that case please open a new issue. 
I'll close this issue instead
thanks
