### ISSUE TITLE
[2.0.12 Bug] 0 Cannot access protected property Joomla\CMS\Menu\MenuItem::$params

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#304]
Hi guys,
PHP 8.1.2 + Joomla 3.10.11 + Helix Ultimate 2.0.11 + SP Page Builder 3.8.9...

- I upgraded SP Page Builder to 4.0.6
- I migrated to Joomla 4.2.5
- I re installed SP Page Builder 4.0.6
- I re installed Helix Ultimate 2.0.11

The site crashed. In the frontend I have back:
0
Cannot access protected property Joomla\CMS\Menu\MenuItem::$params

I attach here an image of the detailed error messages and [this is the page](https://develop.egulp.net/).
![Helix-bug](https://user-images.githubusercontent.com/14607633/206351087-31476b5d-2c05-4481-b406-6d6accc1627d.png)

Be careful:
- Switching again to PHP 7.4.33 does not solve the bug
- Switching to Cassiopeia the site is running

It seems that the BUG is related to Helix Ultimate 2.0.11.
- I investigated and this seems to be a [similar problem](https://issues.joomla.org/tracker/joomla-cms/30463#event-551194)
-  related to the [JMenuItem deprecation](https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#JMenuItem) from Joomla 3.7
- [Here a solution example](https://www.hikashop.com/forum/product-category-display/904320-cannot-access-protected-property.html#341157)
- I'm not a real developer and I cannot help more, but, maybe, Could the …/templates/shaper_helixultimate/features/**title.php** file be the origin of the problem ? (around lines 52 / 67)

Please, Can you help to solve it with a hacking and/or a workaround as soon as possible ?
I'm freezed in the middle of a migration...

**Comment by Savama51** [comment]
They are many few problems with templates/shaper_helixultimate/features/xxx.php ... : 
- Usage of quotes instead of double quotes for src logo images in logo.php
- No way to disable breadcrumb inside title.php
- No simple override possibilty

At this time, you should try to not use the title feature of HU ? Or simply replace title.php by an empty one ?

**Comment by joomleb** [comment]
@Savama51 
many thanks for your reply.

"...At this time, you should try to not use the title feature of HU ?..." = Please, How ? Which is the best way ?

"...Or simply replace title.php by an empty one ?..." = I emptied the .../templates/shaper_helixultimate/features/title.php file and re tested, but I have back the same error messages...

As far as I understand from my testing the problem origin is in Helix Ultimate when used with SP Page Builder 4

**Comment by MarcelSchuermann** [comment]
I have the same Issue with new Version of Joomla & Helix - see this issue:
https://github.com/JoomShaper/helix-ultimate/issues/244

**Comment by joomleb** [comment]
Hi guys, 
I made several tests and I can confirm that the crash happen only with SP Page Builder pages  (Administrator | Component | 4.0.6, other pages like Joomla Articles and Joomla Contact page run perfectly) on Helix Ultimate 2.0.11 (not on Cassiopeia).

Please, Can you confirm the Bug ?

**Comment by mi-prakash** [comment]
Thanks for your feedback.
We will investigate on it.

**Comment by MarcelSchuermann** [comment]
Any information here? How to proceed?
@mi-prakash, @joomleb did you find something?
Please also consider my information in #244

**Comment by mi-prakash** [comment]
@MarcelSchuermann 
Yes, we've notice the issue and in the next version hopefully the issue will be fixed.
Thanks for your support

**Comment by joomleb** [comment]
@mi-prakash 
Joomla 4.2.8 + last Helix Ultimate 2.0.12 - the Bug is still there:
![Helix-Ultimate-2 0 12-params-Bug](https://user-images.githubusercontent.com/14607633/222037709-5c8e2c9b-28ad-4649-9aff-fe4767ff8158.png)

The only temporally workaround is to rename the .../templates/shaper_helixultimate/html/com_sppagebuilder/page/**default.php** file.
Please, Can you confirm and fix it ?

**Comment by mi-prakash** [comment]
@joomleb 
We request you to communicate with this issue in our forum. If that case we can identify your issue clearly. We need specifically check your project files. 
So far we cannot recreate the issue in our testing environment.
https://www.joomshaper.com/forum
Thank you

**Comment by joomleb** [comment]
@mi-prakash
PHP 7.4.33 + Joomla 4.2.8 + last Helix Ultimate 2.0.12 + _SP Page Builder 3.8.9_ > maybe, Is this the reason you cannot replicate it ?!?

I have no access to the forum, but I'm ready to share with you a full access site. Please, Where can I send you full credentials ?

**Comment by mi-prakash** [comment]
@joomleb 
I have no authority to get your files other then forum.
Solving issues requires work, hence support is only for the subscribed members.
Please take a plan and post your issues on the technical support forum. Support team will check your issue.
https://www.joomshaper.com/forum
Thanks understanding

**Comment by ittoufiq** [comment]
> @joomleb I have no authority to get your files other then forum. Solving issues requires work, hence support is only for the subscribed members. Please take a plan and post your issues on the technical support forum. Support team will check your issue. https://www.joomshaper.com/forum Thanks understanding

Can you share your site credentials via our support email? 

support@joomshaper.com

**Comment by joomleb** [comment]
Hi guys, 
@mi-prakash  &  @ittoufiq 
Email sent with full credentials, I remain available...

**Comment by ittoufiq** [comment]
> Hi guys, @mi-prakash & @ittoufiq Email sent with full credentials, I remain available...

Tell me your email address.

**Comment by joomleb** [comment]
@ittoufiq 
Please, Can you confirm the Email reception ?

**Comment by ittoufiq** [comment]
> @ittoufiq Please, Can you confirm the Email reception ?

I received your email and I have shared your site login information with the developer. Hope so, we can update you soon. Thank you

**Comment by ittoufiq** [comment]
Why did you override the page builder? 

`JROOT/templates/shaper_helixultimate/html/com_sppagebuilder/page/default.php:45`

Please watch the video. 

https://drive.google.com/file/d/11a3pp3BzYa6V3uJTanRH6tpNjvBikMnd/view

**Comment by joomleb** [comment]
Hi @ittoufiq 
one week ago I wrote: "...The only temporally workaround is to rename the .../templates/shaper_helixultimate/html/com_sppagebuilder/page/**default.php** file..."

Now, you share a video (thank you), to say me: "rename the file".

So, I don't understand, Would renaming the file be the solution ?!?
Or, Is it just a workaround to don't have back the error ?!?

**Comment by MarcelSchuermann** [comment]
> Thanks for your feedback. We will investigate on it.

Still the same issue for me afer upgrade to Helix V. 4.2.8

**Comment by MarcelSchuermann** [comment]
Now a new bug: When I try to insert a new image in the menu item link, the url is wrong (after selecting the picture).

**Comment by joomleb** [comment]
Hi guys,
@ittoufiq @mi-prakash 
Helix Ultimate 2.0.13 has been released. Please, Can you update is about this bug ?

**Comment by joomleb** [comment]
Hi guys,
2.0.16, as far as I know, this bug has been solved,  Right ? (If confirmed the ticket can be closed).

What experienced here brought us to this feature #313 suggestion that is waiting support...
