### ISSUE TITLE
A bug which is present for a many years!

### ISSUE THREAD

**Issue by 01Kuzma** [JoomShaper/helix-ultimate#305]
This bug lives in a helix for a long time!
What a shame!
I've observed it on [Helix3](https://github.com/JoomShaper/Helix3/issues/119), but it does exists also on Ultimate 2.0.
So, it's present for a several years!!
`plugins/system/helixultimate/core/HelixUltimate.php`

```
	public function bodyClass($class = '')
	{
		$menu = $this->app->getMenu()->getActive();
		$menuParams = empty($menu) ? new Registry : $menu->getParams();


		$stickyHeader 	= $this->params->get('sticky_header', 0) ? ' sticky-header' : '';
		$stickyHeader 	= $this->params->get('sticky_header_sm', 0) ? $stickyHeader . ' sticky-header-md' : $stickyHeader;
		$stickyHeader 	= $this->params->get('sticky_header_xs', 0) ? $stickyHeader . ' sticky-header-sm' : $stickyHeader;

		$bodyClass       = 'site helix-ultimate hu ' . htmlspecialchars(str_replace('_', '-', $this->input->get('option', '', 'STRING')));
		$bodyClass      .= ' view-' . htmlspecialchars($this->input->get('view', '', 'STRING'));
		$bodyClass      .= ' layout-' . htmlspecialchars($this->input->get('layout', 'default', 'STRING'));
		$bodyClass      .= ' task-' . htmlspecialchars($this->input->get('task', 'none', 'STRING'));
		$bodyClass      .= ' itemid-' . (int) $this->input->get('Itemid', '', 'INT');
		$bodyClass      .= ($this->doc->language) ? ' ' . $this->doc->language : '';
		$bodyClass      .= ($this->doc->direction) ? ' ' . $this->doc->direction : '';
		$bodyClass 		.= $stickyHeader;
		$bodyClass      .= ($this->params->get('boxed_layout', 0)) ? ' layout-boxed' : ' layout-fluid';
		$bodyClass		.= ($this->params->get('blog_details_remove_container', 0)) ? ' remove-container' : "";
		$bodyClass      .= ' offcanvas-init offcanvs-position-' . $this->params->get('offcanvas_position', 'right');

		if (isset($menu) && $menu)
		{
			if ($menuParams->get('pageclass_sfx'))
			{
				$bodyClass .= ' ' . $menuParams->get('pageclass_sfx');
			}
		}

		$bodyClass .= (!empty($class)) ? ' ' . $class : '';

		return $bodyClass;
	}
```

This piece of code `$bodyClass       = 'site helix-ultimate hu ' . htmlspecialchars(str_replace('_', '-', $this->input->get('option', '', 'STRING')));` breaks a layout of any component which displays its class in the body. It changes a third-party component's underscore symbol (if it's used) to dash!
For what??? Developers are open to use such a naming convention in their own components.
Then the CSS styles or JS dependent plugins don't work.

For instance, `Phoca Gallery` uses a com_phocagallery class name in the body, it's changed to `com-phocagallery`!!

FIX it ASAP

**Comment by mi-prakash** [comment]
@01Kuzma 
I've notified your problem.
Hopefully there will be a fix for this in the next update and its coming very soon.
Thanks for your patience.

**Comment by Savama51** [comment]
Hi all !

It seems that the piece of code is from `plugins/system/helixultimate/src/Core/HelixUltimate.php` instead of `plugins/system/helixultimate/core/HelixUltimate.php`.

It's not the only bug that remains since v2.0, but looking at the 2.0.12 release, i don't see underscore replace anymore !
Well done dev team !

@01Kuzma, It's maybe time to close thise issue ?

**Comment by 01Kuzma** [comment]
@Savama51, I've checked now. They have made that now plugin class is duplicated and displayed twice, with an underscore, as is (finally!), and how it was previously: `com_phocagallery and com-phocagallery`

**Comment by mi-prakash** [comment]
I think this issue can be closed. 
thanks all for your support and patience
