### ISSUE TITLE
Sharer (Facebook, LinkedIn, Twitter) does not work after J4 Upgrade

### ISSUE THREAD

**Issue by MarcelSchuermann** [JoomShaper/helix-ultimate#306]
=> Solved: **Problem only occurs on localhost where there is no valid URL (https:/)**.

### Steps to reproduce the issue
- Create a J4 detail article page
- Activate Sharing buttons (Facebook, LinkedIn, Twitter)
- Click on the button to share via Facebook

### Expected result
- FB-Window opens
- Post should be created with a link to the article detail page

### Actual result
- FB-Window opens
- Error occurs: `Parameter 'href' should represent a valid URL`

### System information (as much as possible)
- J4 v. 4.2.6
- MariaDB v. 10.4.19
- PHP v. 8.0.7

### Additional comments
- Same with LinkedIn sharer
- Maybe same with other sharers

**Comment by mi-prakash** [comment]
@MarcelSchuermann 
We have tested with multiple developers, none of us having this issue
Please share us with more details. You can post your problem in our forums 
https://www.joomshaper.com/forum

**Comment by MarcelSchuermann** [comment]
@mi-prakash Thanks a lot for testing and your feedback!

It seems like the problem **only occurs on localhost** because the share-URL does not contain a valid URL (https://).
Therefore this can be closed. Thanks a lot for the support!

**Comment by mi-prakash** [comment]
@MarcelSchuermann 
Thank you for your feed back.
closing the issue
