### ISSUE TITLE
[2.0.1 to 2.0.13] Problem with pagination layout

### ISSUE THREAD

**Issue by Savama51** [JoomShaper/helix-ultimate#312]
### Steps to reproduce the issue

Create a category with 2 articles (or more)
Create a blog category menu with the previous category created, display only one article par page.

### Expected result

The category menu is displayed with pagination bloc.
Source of pagination has to be in correct html tags order :

`<ul class="pagination ms-0 mb-4">`
`<li class="pagination-start disabled page-item">`
`<span class="page-link" aria-hidden="true"><span class="fas fa-angle-double-left" aria-hidden="true"></span></span>`
`</li>`
`<li class="pagination-prev disabled page-item">`
`<span class="page-link" aria-hidden="true"><span class="fas fa-angle-left" aria-hidden="true"></span></span>`
`</li>`
`<li class="page-item disabled">`
`<span aria-current="true" aria-label="Page 1" class="page-link">1</span>`
`</li>`
`<li class="page-item">`
`<a aria-label="Page 2" href="/index.php/uncategorized?start=1" class="page-link">2</a>`
`</li>`
`<li class="pagination-next page-item">`
`<a aria-label="Next page" href="/index.php/uncategorized?start=1" class="page-link"><span class="fas fa-angle-right" aria-hidden="true"></span></a>`
`</li>`
`<li class="pagination-end page-item">`
`<a aria-label="Last page" href="/index.php/uncategorized?start=1" class="page-link"><span class="fas fa-angle-double-right" aria-hidden="true"></span></a>`
`</li>`
`</ul>`

### Actual result

Double usage of li tag :

`<ul class="pagination ms-0 mb-4">`
`<li class="pagination-start disabled page-item">`
`<li class="disabled page-item">`
`<span class="page-link" aria-hidden="true"><span class="fas fa-angle-double-left" aria-hidden="true"></span></span>`
`</li>`
`</li>`
`<li class="pagination-prev disabled page-item">`
`<li class="disabled page-item">`
`<span class="page-link" aria-hidden="true"><span class="fas fa-angle-left" aria-hidden="true"></span></span>`
`</li>`
`</li>`
`<li class="page-item disabled">`
`<li class="active page-item">`
`<span aria-current="true" aria-label="Page 1" class="page-link">1</span>`
`</li>`
`</li>`
`<li class="page-item">`
`<li class="page-item">`
`<a aria-label="Page 2" href="/zindex.php/uncategorized?start=1" class="page-link">2</a>`
`</li>`
`</li>`
`<li class="pagination-next page-item">`
`<li class="page-item">`
`<a aria-label="Next page" href="/index.php/uncategorized?start=1" class="page-link"><span class="fas fa-angle-right" aria-hidden="true"></span></a>`
`</li>`
`</li>`
`<li class="pagination-end page-item">`
`<li class="page-item">`
`<a aria-label="Last page" href="/index.php/uncategorized?start=1" class="page-link"><span class="fas fa-angle-double-right" aria-hidden="true"></span></a>`
`</li>`
`</li>`
`</ul>`

### System information (as much as possible)

Joomla 4.2.8
Helix Ultimate 2.0.12

### Additional comments

I think problem is with usage of li tag in `overrides\layouts\joomla\pagination\link.php` while li tag is already used in `overrides\layouts\joomla\pagination\list.php`

**Comment by mi-prakash** [comment]
@Savama51 
Thanks for your feedback on this, we have found the issue
The issue will be fixed on the next update.

**Comment by Savama51** [comment]
Hi,
any news about this issue ?

**Comment by mi-prakash** [comment]
@Savama51 
hello,
the latest 2.0.13 update should fix this issue. Have u tested with the latest build ?

**Comment by Savama51** [comment]
Hi,
Well sorry about that but nothing has changed about this issue.

And looking to source code of files `overrides\layouts\joomla\pagination\link.php` and `overrides\layouts\joomla\pagination\list.php`, no change at all between 2.012 and 2.0.13.

**Comment by mi-prakash** [comment]
@Savama51 I'm really sorry. This is under development. you will get the fix on the next update
So please be patient, the next update is coming soon

**Comment by Savama51** [comment]
I've just checekd on latest version (2.0.14), it seems to be ok now !
Thanks.
