### ISSUE TITLE
[2.0.16 Bug] .input-password-toggle CSS > fixing

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#314]
Hi guys, 
 .../templates/shaper_helixultimate/css/**template.css**  file, about the:

.login .password-group button.input-password-toggle {  
  background-color: #eaecef;
  border-color: #ced4da;
  color: #212529;
}

.login .password-group button.input-password-toggle 
the **.login .password-group** should be deleted

to have it working on both, Login page and Registration page + Profile Editing page + Password Resetting Compete page process...

Please, Can you confirm and apply the fix ?

**Comment by joomleb** [comment]
...Please, Can you confirm and apply the fix ?

**Comment by joomleb** [comment]
@mi-prakash 
...Please, Can you confirm and apply the fixing ?

**Comment by joomleb** [comment]
Hi guys,
2.0.16 unfortunately not added. 
Please, Can you confirm annoing bug and add this fixing as suggested ?

It takes just one minute or two...

**Comment by mi-prakash** [comment]
@joomleb 
The password toggle is working just fine. What is your issue here???

Uploading Screen Recording 2023-10-26 at 12.50.07 PM.mov…

**Comment by mi-prakash** [comment]
i've just told you, I've tested in all pages including Login page and Registration page + Profile Editing page + Password Resetting Compete page process...

**Comment by joomleb** [comment]
Hi @mi-prakash 
sorry, but, into the Registering, Login etc. pages mentioned, when you click into a field to input values, a blue border field is highlighted, Right?
Well, as you can see the blue borders input **psswords** fields are totally different (bigger) than all the others borders input fields.
I attach 6 images here for you.
You can test it on these pages:
https://test4.egulp.net/index.php/registration
https://test4.egulp.net/index.php/login
![Screenshot_20231027-040041970](https://github.com/JoomShaper/helix-ultimate/assets/14607633/f2c3cbb2-7ffb-4693-a642-56363d6869a8)
![Screenshot_20231027-040051375](https://github.com/JoomShaper/helix-ultimate/assets/14607633/0f1c632d-f132-4e8c-969a-ff11f14c612c)
![Screenshot_20231027-040118241](https://github.com/JoomShaper/helix-ultimate/assets/14607633/929f372a-e567-4455-9cbb-ecb1f75f5df5)
![Screenshot_20231027-040131777](https://github.com/JoomShaper/helix-ultimate/assets/14607633/2776c2ba-c17f-423c-8a81-9b3a83de699d)
![Screenshot_20231027-040144503](https://github.com/JoomShaper/helix-ultimate/assets/14607633/d74040d0-c144-4092-8ea7-beadad77ca9a)
![Screenshot_20231027-040218393](https://github.com/JoomShaper/helix-ultimate/assets/14607633/1d95f090-2733-4bdf-867e-300c90f754e4)

Can you see them ?

**Comment by mi-prakash** [comment]
@joomleb 
this is just a css issue, and it will be fixed in the next update.
The issue is already fixed in our current development version

**Comment by joomleb** [comment]
@mi-prakash thank you

**Comment by mi-prakash** [comment]
`input[type="text"],
input[type="email"],
input[type="url"],
input[type="date"],
input[type="password"],
input[type="search"],
input[type="tel"],
input[type="number"],
textarea {
  outline: none;
  box-shadow: none !important;
}`

Use this on custom css...hopefully it will fix the issue

**Comment by joomleb** [comment]
@mi-prakash 
I'm going to close this as fixed with the 2.0.17 release, thank you
