### ISSUE TITLE
[2.0.16 Bug]  :focus CSS conflict > fixing

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#317]
Hi guys, 
PHP 7.4.33 + Joomla 4.3.2 + Helix Ultimate 2.0.13 (no Custom CSS)
I noted this conflict on:
- [Login page](https://develop.egulp.net/login)
- [Registration page](https://develop.egulp.net/registracion)
But sure it will be replicated in other forms.

Pay attention to the box-shadow border dimension when :focus, as far as I understand, to the Password and Email fields the Bootstrap CSS from the …/templates/shaper_helixultimate/css/**bootstrap.min.css**  file is applied (I suppose it is the standard Bootstrap 5):

`form-control:focus {
  color: #212529;
  background-color: #fff;
  border-color: #86b7fe;
  outline: 0;
  box-shadow: 0 0 0 0.25rem rgb(13 110 253 / 25%);
}`

While it is not applied to the _Name_ and _Username_ fields.
I'm not able to understand where the conflict is coming.

Please, Can you confirm it ?
Do you have a quick workaround to fix it ?

**Comment by joomleb** [comment]
Thanking Alex (alzander) from [SourceCoast](https://www.sourcecoast.com/forums/jfbconnect-9-support/14091-9-0-215-bug-focus-css-conflict#68503)
the bug seems to come from .../templates/shaper_helixultimate/css/**template.css**

input[type="text"], textarea {
  outline: none;
  box-shadow: none !important;
}

I tested and Yes, excluding it solves the bug.
Please, Can you confirm the fixing ?

**Comment by joomleb** [comment]
...Please, Can you confirm and apply the fix ?

**Comment by joomleb** [comment]
@mi-prakash 
Please, Can you confirm the fixing and add it to the upcoming next HU release ?

**Comment by joomleb** [comment]
Hi guys,
this is a simple fixing suggestion, not yet added into 2.0.16.
It takes just one or two minutes to check and to add it...

Please, Can you add it ?

**Comment by mi-prakash** [comment]
@joomleb 
I've added a fix, It will be added on the next update

**Comment by joomleb** [comment]
@mi-prakash
I'm going to close this as fixed with the 2.0.17 release, thank you
