### ISSUE TITLE
[2.0.13]  Error on frontend Undefined variable $scssVars

### ISSUE THREAD

**Issue by Twin02Daddy** [JoomShaper/helix-ultimate#337]
### Steps to reproduce the issue
Installed Plug 2.0.13

ERRORS :
Undefined variable $scssVars
&
Warning: Trying to access array offset on value of type null in
plugins/system/helixultimate/src/Core/HelixUltimate.php on line 1914

**Comment by joomleb** [comment]
@Twin02Daddy 
Please, Can you replicate / confirm the issue with the last Joomla 4.4.5 + Helix Ultimate 2.1.1 ?
(Which version of PHP are you running?)

OR, Can we consider it as "solved",?
