### ISSUE TITLE
[2.0.14 Bug] Menu Item > Link Type > Link Icon class

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#346]
Hi guys,
PHP 7.4.33 + Joomla 4.3.3 + Helix Ultimate 2.0.14
Menu Item home (for ex.) > Link Type > Link Icon class: fas fa-home (for ex.)

The font awesome Home icon is not shown in the Menu Item title (it is running perfectly, as expected, with the default Cassiopeia template)

Please, Can you address us on How to fix the bug ?
[A "conflict" cannot be the explanation](https://www.joomshaper.com/forum/question/7179)  because I tested it on a clean Joomla 4 new installation

**Comment by joomleb** [comment]
@ahamed @mi-prakash 
...Please, Can you confirm and suggest a quick fixing ?

**Comment by mi-prakash** [comment]
@joomleb 
Thanks for the feedback. I've found the issue
Hopefully it'll be fixed on next update
Best regards

**Comment by joomleb** [comment]
@mi-prakash Thank you very much for your confirmation. I studied it and tried to solve the bug without success. Hooping to help you on solving, I leave here some useful informations:

**1** - Has this Helix Ultimate bug been solved ?
 https://github.com/joomla/joomla-cms/issues/37871#issuecomment-1137360237

**2** - [Font Awesome 5 pseudo-elements](https://fontawesome.com/v5/docs/web/advanced/css-pseudo-elements)  fas "Solid" are free, but also fab "Brands" are free. To call "Font Awesome 5 Free" does not call Brand fab, to call them we have to call "Font Awesome 5 Brands".
So, [both families should be called](https://stackoverflow.com/questions/62239119/font-awesome-5-why-dont-brand-icons-work-when-using-font-face), something like:
font-family: 'Font Awesome 5 Free','Font Awedome 5 Brands';

**3** - I did not understand if the "font-weight: 900" for fas Solid has been fixed in the last FA5 release (some icons in font awesome 5 not working without font-weight: 900;)

**4** - Joomla 5 will introduce FA6 https://github.com/joomla/joomla-cms/pull/36906#issuecomment-1245807206
and [Font Awesome icon packs are not backward compatible](https://fontawesome.com/v6/docs/web/setup/upgrade/pseudo-elements#contentHeader) . Fas become fa-solid and fab fa-brands

**5** - Can be that the .../templates/shaper_helixultimate/css/template.css file:
li>a:before{display:none}
is generating the issue ?

**6** - Can be that the [Single-Colon](https://css-tricks.com/to-double-colon-or-not-do-double-colon/#:~:text=Technically%2C%20the%20correct%20answer%20is,colon%20selectors%20are%20pseudo%2Delements.) is generating an issue ?

**7** - Can be useful [this Joomla 4 Forum discussion](https://forum.joomla.org/viewtopic.php?f=803&t=981037)  ?

**Comment by joomleb** [comment]
@mi-prakash 
Today I saw the Helix Ultimate 2.0.15 release, in the changelog:
- Menu icon not working

So, I installed a new test Joomla 4.3.4 site and I installed last Helix Ultimate, you can see it running [here](https://test4.egulp.net/) 

As far as I tested:
- A - the Link Icon class (fas and fab) are runnings, thank you
- **B** - into the Offcanvas the icon is not following the menu item color. In my opinion that should be the default behaviour, Do you agree?
- **C** - I'm a "responsive, non-waster of space" supporter. Please, Can you set the margin-right in rem as ... ?: 
margin-right: **.4rem;**

**D** - Please, What is the Helix Ultimate plan for Joomla 5 /Font Awesome 6 ?

**Comment by joomleb** [comment]
@mi-prakash 
2.0.16 has been released.-As far as I see we can consider this as "solved", Right ?
If so, you can close this to keep GitHub clean.

(I cannot check because I'm traveling) Please, What is your decision on point "C" ?

**Comment by joomleb** [comment]
@mi-prakash 
Be careful, this bug is not solved for me, because you added a fixed "p-2" attribute class to the Link Icon class.
That is spacing also on the left side, moving all the menu items on the right and creating confusion with the sub menu items that are not using icons.

It should be "pe-2"
https://getbootstrap.com/docs/5.3/utilities/spacing/
Please, Can you confirm it ?
Please, Where can we manually edit and fix it ?

Please, Why you choose to add there a padding space instead of a margin space ?

**Comment by mi-prakash** [comment]
@joomleb 
sorry for misunderstanding
i've checked it, generally p-2 wont seems having any issue but yes `pe-2` will be a better solution here
we will try to improve this in the neext update using pe-2
in the meantime the issue remains closed. if in the next update u still have any issue, open another issue in git
thank you for understanding

**Comment by joomleb** [comment]
@mi-prakash thank you for your reply.
Sure, I'll stay tuned.
Please, What is the file I can manually edit to change it to pe-2 ?
Can you address me?

**Comment by joomleb** [comment]
Hi @mi-prakash 
I found the same bug on standard Joomla Cassiopeia.
I discussed it here https://github.com/joomla/joomla-cms/issues/42368. and I'm waiting the PR https://github.com/joomla/joomla-cms/pull/42415 merging.

From my point of view "no predefined spacing attribute class" is better then "pe-2" class.
Sire, it cannot be "p-2".

Here the Helix Ultimate:overrides from Joomla
- …/plugins/system/helixultimate/overrides/mod_menu/default_component.php - line 39 < …/modules/mod_menu/tmpl/default_component.php - line 44 and 47
- …/plugins/system/helixultimate/overrides/mod_menu/… line 24 < …/modules/mod_menu/tmpl/default_heading.php - line 23 and 26
- …/plugins/system/helixultimate/overrides/mod_menu/… line 24 < …/modules/mod_menu/tmpl/default_separator.php - line 23 and 26
- …/plugins/system/helixultimate/overrides/mod_menu/… line 38 < …/modules/mod_menu/tmpl/default_url.php - line 36 and 39

Waiting for your confirmation, thanks...

**Comment by joomleb** [comment]
@mi-prakash as far as I see into the 2.0.18 release, you choosen to add the pe-2 attribute class (instead of nothing).
Please, Can you confirm ?
(Just to know it to give us the opportunity to organize our works, thank you in advance)

**Comment by mi-prakash** [comment]
yes

**Comment by joomleb** [comment]
Hi @mi-prakash 
I'm back here because
PHP 8.1.26 + Joomla 4.4.1 + Helix Ultimate 2.0.18

The "B" issue: "...into the Offcanvas the icon is not following the menu item color. In my opinion that should be the default behaviour,.."
mentioned here https://github.com/JoomShaper/helix-ultimate/issues/346#issuecomment-172154511. seems to be just partially solved because now:

f I add:
Menu Item > Link Type > Link class: blabla

And then into the Custom CSS
a.blabla span {
  color: #ce1126;
}

The color is not applied to the menu icon into the Offcanvas position, while it is applied correctly outside the Offcanvas position.

Is it due for an abuse of the important attribute (strongly discouraged) #318  OR for a "span" missing into the Offcanvas ?

Please, What is the right way to solve it ?
