### ISSUE TITLE
[2.0.16] FontAwesome 5/6 confusion under J4

### ISSUE THREAD

**Issue by Savama51** [JoomShaper/helix-ultimate#368]
### Steps to reproduce the issue

On a fresh Joomla 4 install, create a menu with submenu.

### Expected result

On frontend, a caret should be displayed next to the menu item containing sub-element.

### Actual result

On frentend, a weird icon is displayed next to the menu item containing sub-element.

### System information (as much as possible)

Joomla 4.4.0
HelixUltimate 2.0.16
"Activate FontAwesome" is activated in template settings.

### Additional comments

Looking into code source, we can observe in template.css that they are some selector with "Font Awesome 6 Free" font calls... BUT FA6 is still not included in latest Joomla! 4, only from Joomla! 5...
The actual workaround is to rewrite all "Font Awesome 6 Free" to "Font Awesome 5 Free" in a custom.css ... weird

**Comment by joomleb** [comment]
@mi-prakash 
Please, Can you confirm?  How should we behave ?  Can we update HU 2.0.16 on Joomla 4.4.x?  What is the simplest workaround on the fly?

**Comment by joomleb** [comment]
@mi-prakash 
Please, Would HU 2.0.17 rel. be the answer ?

**Comment by Savama51** [comment]
Form my tests, the problem is still remaining under 2.0.17.

**Comment by Savama51** [comment]
Hi,
Looking to this issue in latest HU 2.1.1, it seems to be ok for now.
So I close the ticket.
