### ISSUE TITLE
[2.0.17] J!4 users report errors - sites not running after update

### ISSUE THREAD

**Issue by pepperstreet** [JoomShaper/helix-ultimate#372]
### Steps to reproduce the issue

Just reporting for some other users.
Personally, I can't re-create the issue on my local environment.

### Actual result

Other users reported the following issues: 

- error: 0 - Call to a member function get() on null
- error 500

### System information (as much as possible)

J!3.10 , updated from HU2.0.11 -> 12 -> 16 -> HU2.0.17 works :)
J!4.4 , updated from HU2.0.11 -> 12 -> 16 -> HU2.0.17 works :)

PHP 7.4 and 8.1.13

### Additional comments

Related Forum thread 
https://www.joomshaper.com/forum/question/28606

**Comment by joomleb** [comment]
Hi @pepperstreet 
it would be good if the users could enable the Joomla Developer mode + Error Reporting to maximum and report here the complete error messages

**Comment by hmed95** [comment]
Hello, i get errors too, here more information if you can help us please :

`Call stack
#   Function    Location
1   ()  JROOT/plugins/system/helixultimate/overrides/mod_menu/default_component.php:52
2   require()   JROOT/templates/finion/html/mod_menu/default_component.php:11
3   require()   JROOT/plugins/system/helixultimate/overrides/mod_menu/default.php:95
4   require()   JROOT/templates/finion/html/mod_menu/default.php:11
5   require()   JROOT/modules/mod_menu/mod_menu.php:30
6   include()   JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:52
7   Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}()   JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:55
8   Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch()  JROOT/libraries/src/Helper/ModuleHelper.php:281
9   Joomla\CMS\Helper\ModuleHelper::renderRawModule()   JROOT/libraries/src/Helper/ModuleHelper.php:161
10  Joomla\CMS\Helper\ModuleHelper::renderModule()  JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:99
11  Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render()  JROOT/libraries/src/Document/Renderer/Html/ModulesRenderer.php:50
12  Joomla\CMS\Document\Renderer\Html\ModulesRenderer->render() JROOT/libraries/src/Document/HtmlDocument.php:565
13  Joomla\CMS\Document\HtmlDocument->getBuffer()   JROOT/libraries/src/Document/HtmlDocument.php:833
14  Joomla\CMS\Document\HtmlDocument->_renderTemplate() JROOT/libraries/src/Document/HtmlDocument.php:637
15  Joomla\CMS\Document\HtmlDocument->render()  JROOT/libraries/src/Application/CMSApplication.php:1025
16  Joomla\CMS\Application\CMSApplication->render() JROOT/libraries/src/Application/SiteApplication.php:724
17  Joomla\CMS\Application\SiteApplication->render()    JROOT/libraries/src/Application/CMSApplication.php:298
18  Joomla\CMS\Application\CMSApplication->execute()    JROOT/includes/app.php:61
19  require_once()  JROOT/index.php:32`

**Comment by hmed95** [comment]
I disabled the offcanvas menu module and the website is working again,  seems to be related to this.
i use Finion template.

Can you share a fix or update please ?

**Comment by pepperstreet** [comment]
Issue seem to be solved. Silent update. Please, **re-download v2.0.17** system plugin only!
