### ISSUE TITLE
[2.0.18 Bug] Password - Min requirements not grabbed

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#378]
Hi guys,
PHP 7.4 / 8.1 + Joomla 4.4 + Helix Ultimate 2.0.17

The Helix Ultimate Registration page is not grabbing the "Minimum Requirements" from
Joomla Users Options > Password Options > Minimum Password Length... etc.

Here an image for you: https://photos.app.goo.gl/gmguWctFb2SHxBM97

@mi-prakash 
Please, Can you confirm ?
Can you suggest here the fixing code to add ?

**Comment by mi-prakash** [comment]
@joomleb this will be added in the next update

**Comment by joomleb** [comment]
I can confirm that has been fixed with the 2.0.18 release, thank you!
I"m going to close this ticket...

**Comment by joomleb** [comment]
@mi-prakash 
Please, Can you answer to my question 1 and help on 2 & 3 points ?

**Comment by mi-prakash** [comment]
@joomleb thanks for the feed back
in the following update we will definitely add those
ur feed backs are noted.
if everything is ok thill no, u can close the issue 
thanks

**Comment by mi-prakash** [comment]
@joomleb 
As you can see in the screenshot, It also works on the Profile edit page
are you having any issue with that.
<img width="942" alt="image" src="https://github.com/JoomShaper/helix-ultimate/assets/42798816/330593f6-0d20-401d-9808-b85814f74e8c">

**Comment by joomleb** [comment]
@mi-prakash 
Is your image from Joomla 4.x or 5.x ?
With J 4 is NOT running for me.Can you confirm ?
Do it depend on Joomla?
Please, Is there a way with Helix Ultimate to force to show "Min Req" also on Joomla 4 ?

**Comment by mi-prakash** [comment]
@joomleb 
it is on J5 and i think its dependen with Joomla version
as you can see in Cassiopeia template it is not visible on Joomla 4 also

**Comment by joomleb** [comment]
Hi @mi-prakash 
Thank you for your reply.
So, as far as I understand from your reply, the answer to:
"...Please, Is there a way with Helix Ultimate to force to show "Min Req" also on Joomla 4 ?..."
It is: No.

Mmmm, no chances ...It is time to move _quickly_ all our sites to J5...
