### ISSUE TITLE
Attempted to call an undefined method named "sanitizeAssetsForJ5" of class "PlgSystemHelixultimate"

### ISSUE THREAD

**Issue by sousa9g** [JoomShaper/helix-ultimate#392]
### Steps to reproduce the issue

Visiting the Template Options in backend

### Expected result

The template options page

### Actual result

Attempted to call an undefined method named "sanitizeAssetsForJ5" of class "PlgSystemHelixultimate".

/plugins/system/helixultimate/helixultimate.php:392

### System information (as much as possible)

Joomla 5.0.2 + Helix Ultimate 2.0.18

**Comment by mi-prakash** [comment]
this issue has been fixed
