### ISSUE TITLE
[2.0.18 Bug] Registration page with RAV4

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#393]
Hi guys,
PHP 8.1.27 + Joomla 4.4.3 + Helix Ultimate 2.0.18 + RAV4 1.0.0
I installed the system [Registration Address Validation plugin](https://www.kuneze.com/downloads/rav4) (RAV4)

[Test 3](https://test3.egulp.net/registration)
As you can see, with Cassiopeia (and others templates), it adds also a div#jform_f90validationcode-desc with a text note, here an image for you:

![Screenshot_20240312-090635~2](https://github.com/JoomShaper/helix-ultimate/assets/14607633/a409fc35-8784-499e-9df6-86c4f1b04a32)

[Test 1](https://test1.egulp.net/registracion)
As you can see, it is not shown with Helix Ultimate. (Logically I tested it on the same Test 3 site). Really a singular Bug, I investigated, but I do not understand what it is causing it.

@mi-prakash 
Please, Can you help on it? Do you have any suggestion?

**Comment by joomleb** [comment]
Hi @mi-prakash 
Please, Is it a confirmed bug ? ...I remain available...

**Comment by mi-prakash** [comment]
@joomleb 
i haven't checked it yet, 
will let you know when i check this issue

**Comment by mi-prakash** [comment]
@joomleb 
i was checking the issue and came to know RAV4 is a paid extension, am i right?
If that so i can't have access of the plugin

**Comment by joomleb** [comment]
> @joomleb i was checking the issue and came to know RAV4 is a paid extension, am i right? If that so i can't have access of the plugin

Yes,  you can. Just let me know where I can contact you (send it to you)...

**Comment by joomleb** [comment]
@mi-prakash Yes, you can. Please, just let me know where I can contact you (send it to you)...

**Comment by mi-prakash** [comment]
@joomleb 
please open a support ticket in our forum, and contact there with the support team because I'm not allowed to communicate this kinds of information in here
https://www.joomshaper.com/forum

**Comment by joomleb** [comment]
@mi-prakash 
You can download RAV4 plugin for direct testing from [here](https://mega.nz/file/6X4kmBwA#v_yxJSsgvZfj6G-sxceEV1k9-kNVUdMppTG37C3nHgY)

Please, advice me here when downloaded... Thanks You

**Comment by joomleb** [comment]
@mi-prakash 
You can download RAV4 plugin for direct testing from [here](https://mega.nz/file/6X4kmBwA#v_yxJSsgvZfj6G-sxceEV1k9-kNVUdMppTG37C3nHgY)

Please, advice me here when downloaded... Thanks You

**Comment by joomleb** [comment]
Hi @mi-prakash
I cannot find any specific note on the last change log, but with Helix Ultimate 2.1.0 + Joomla 4.4.4 this bug seems has been fixed, thank you.
Before to close this ticket, Please, Can you confirm it ?

**Comment by mi-prakash** [comment]
@joomleb 
We have updated the user overrides. that fixed your problem.
Closing this ticket
thank you
