### ISSUE TITLE
Countdown On Coming Soon Page Not Working On v2.1.1

### ISSUE THREAD

**Issue by Molasar49** [JoomShaper/helix-ultimate#411]
### Steps to reproduce the issue
On the Advanced Tab, Coming Soon section, add any future date to the Date field, i.e., 2024-12-04 and save. Enable Coming Soon set to "On" position.

Front-end shows 00:00:00:00

### Expected result
Animated countdown

### Actual result
Front-end shows 00:00:00:00

### System information (as much as possible)
Helix Ultimate Framework v.2.1.1
Running on Joomla v5.1.1
Ubuntu Server 22.04.4 LTS

SP Page Builder UI Countdown add-on works on other pages.

### Additional comments
Don't remember if this issue happened on a previous version of the Helix Ultimate Framework

**Comment by Savama51** [comment]
I've just tested countdown on a fresh Joomla! install, and it's working.

PHP 8.2.5
Apache 2.4.57).
Joomla! 5.1.1
Hleix Ultimate 2.1.1

I don't have SP Page Builder, maybe you should investigate here.

**Comment by Molasar49** [comment]
Well, not SP Page Builder, but this:

If I put 
`2024-12-04`
on the Date textbox, I get this 
`<div class="uk-grid-small uk-child-width-auto uk-flex-center uk-margin-large uk-grid uk-countdown" uk-grid="" uk-countdown="date: 2024-12-04 00:00:00T14:20:15+00:00" role="timer">`
on the page

If I manually edit it to:
`<div class="uk-grid-small uk-child-width-auto uk-flex-center uk-margin-large uk-grid uk-countdown" uk-grid="" uk-countdown="date: 2024-12-04T14:20:15+00:00" role="timer">`
it starts working.

If I put 
`2024-12-04T22:00:00+00:00`
on the Date textbox, I get this

`<div class="uk-grid-small uk-child-width-auto uk-flex-center uk-margin-large uk-grid uk-countdown" uk-grid="" uk-countdown="date: 2024-12-04 22:00:00T14:20:15+00:00" role="timer">
`
on the page

which leads me to believe something is wrong in the comingsoon.php file here:

`        <?php if($params->get('comingsoon_date')) : ?>
          <?php $comingsoon_date = $params->get("comingsoon_date"); ?>

          <div class="uk-grid-small uk-child-width-auto uk-flex-center uk-margin-large" uk-grid uk-countdown="date: <?php echo $comingsoon_date; ?>T14:20:15+00:00">`

or in the way $params->get "gets" the parameter.

**Comment by Molasar49** [comment]
Ok, deleted the
`T14:20:15+00:00`
from the php file and it's working now. So, this is definitely a bug included in the php file.

**Comment by Savama51** [comment]
Sorry mate, can't find your exemple code in original HU 2.1.1 files... Are you using overriding for comingsoon.php layout file ?

**Comment by Molasar49** [comment]
Found it. It's on the vhost_free_j5_2.1.7 and vhost_free_j5_2.1.8 templates. Different company and different product!

Sorry, my bad!

**Comment by Savama51** [comment]
So then don't forget to close this ticket :)

**Comment by Molasar49** [comment]
Not applicable - different company and different product.
