### ISSUE TITLE
A menu item should render as a normal menu item when it has hidden children only

### ISSUE THREAD

**Issue by horvathcsabazoltan** [JoomShaper/helix-ultimate#54]
When you leverage Joomla's menu item hiding feature, and a menu has only hidden items it renders as a paren menu item (with a submenu indicator '>') and its submenu is empty. 

The solution would be to remove items with 'menu_show' => 0 param in initMenu() (plugins\system\helixultimate\core\classes\menu.php):
```
foreach ($items as $key => $item)
{
    $item_params = new \Joomla\Registry\Registry;
    $item_params->loadString($item->params);

    if (!$item_params->get('menu_show', 0))
    {
        unset($items[$key]);
    }
}
```

**Comment by mdamjadrana** [comment]
Its' Already Solved
