### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by woluweb** [JoomShaper/helix-ultimate#56]
Hi,
When using Helix Ultimate, there are 3 errors in the Browser's console : 
DevTools failed to parse SourceMap: /templates/shaper_helixultimate/js/bootstrap.min.js.map
DevTools failed to parse SourceMap: /templates/shaper_helixultimate/css/bootstrap.min.css.map
DevTools failed to parse SourceMap: /templates/shaper_helixultimate/js/popper.min.js.map

Can you please fix this ?
Txs !

**Comment by mdamjadrana** [comment]
Already Solved
