### ISSUE TITLE
Need for custom.scss (or equivalent like user.scss)

### ISSUE THREAD

**Issue by woluweb** [JoomShaper/helix-ultimate#60]
Hi,
This issue refers to https://www.joomshaper.com/forums/how-to-add-custom-scss

The use of scss is a great plus for Helix Ultimate.
custom.css does work, like in good old Helix3

But there is the need to have some custom.scss, otherwise all the customiszation are lost at every update of Helix Ultimate (like I had the bad experience with the last update in August ;) )

**Comment by ahamed** [comment]
Hello @woluweb,

You can use a custom SCSS file in your **Helix Ultimate** powered templates from now.

Just create a file named `custom.scss` at `templates/shapre_helixultimate/scss` directory and enable the option `Compile SCSS to CSS` option from `Advanced > SCSS`.

![image](https://user-images.githubusercontent.com/5783354/96723393-554a7380-13d0-11eb-98c6-6452bc8ffa69.png)
