### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by TheStingPilot** [JoomShaper/helix-ultimate#71]
Hello,

On the page http://domain.com/joomla/administrator/index.php?option=com_ajax&helix=ultimate&id=12 I receive an error 500 Unable to load render class.

![2020-06-26 09_43_11-Helix Ultimate Framework and 5 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/67457660/85833157-9370b700-b791-11ea-9ddf-a646ecfe76fa.png)

With kind regards,
TheStingPilot

**Comment by ahamed** [comment]
Hello @TheStingPilot,
I cannot visit your link.

![image](https://user-images.githubusercontent.com/5783354/85840548-77373f00-b7be-11ea-8a22-f0ef45f7eccb.png)

**Comment by TheStingPilot** [comment]
That is correct. The domainname is an example.
