### ISSUE TITLE
Offcanvas Close "X" > deprecated - improvement

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#73]
Hi guys, 
PHP 7.3.19 + Joomla 3.9.19 + Helix Ultimate 2.0 alpha - [url=https://photos.app.goo.gl/NbxFhWt3o3hboMuT6]I attach an image[/url] as example - [url=https://test2.egulp.net/]here the test site[/url]

[b]Close[/b] "[b]X[/b]"
To save useless space is really too important (width and height), Google has deprecated it on all her Apps like Google Drive and Google Photo, this because a click outside the Offcanvas always (on all screen dimensions) close it. 
Please, Can you take over it and/or to create a an option to not use it ?

**Comment by mdamjadrana** [comment]
Sorry, we are don't do custom work.
