### ISSUE TITLE
Header scroll down > to hide - improvement

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#74]
Hi guys,
about Header, to save useless space is really too important, Google has long added the feature on all her Apps like Google Drive and Google Photo, [here a video example for you](https://photos.app.goo.gl/oPp4kDPiJfaQTZb68)
When scroll down the Header should always disappear (on all screen dimensions) while a small scroll up restores it
Please, Can you consider it for the 2.0 beta / stable release ?

**Comment by raysr01** [comment]
I second that

**Comment by joomleb** [comment]
Hi @raysr01 
hoping Joomshaper team is alive, many thanks for your vote!

@ahamed 
in my opinion the two tickets should / could be merged

**Comment by mdamjadrana** [comment]
Sorry, we are don't do custom work.
