### ISSUE TITLE
 Helix Ultimate 2 Alfa single Header bug

### ISSUE THREAD

**Issue by pavel-ww** [JoomShaper/helix-ultimate#76]
Hi guys.

If it is used single predefined header or custom header (with the sticky option turned on), and above it there is no section with content like the top bar, header always gets a static "header-sticky" class.

Many users use this class to customize the header before and after the scroll.

After the update, this will lead to the breakdown of many sites. Therefore, you should take care to maintain this feature for custom header using, without sections above it.
![1](https://user-images.githubusercontent.com/67497496/85943942-1cc3ed00-b93c-11ea-9aa1-42d971e8f140.jpg)
And in addition, the header in this form overlaps the SP PB "edit page" button

![2](https://user-images.githubusercontent.com/67497496/85943944-1df51a00-b93c-11ea-8644-c7bd14b27ff2.jpg)

**Comment by pavel-ww** [comment]
Also, I want to draw your attention to the fact that the issue of Hader stability is not resolved. You began to use position: absolute instead of a trick using
`#sp-header.header-sticky ~ section#sp-main-body {
	padding-top: HEADER_HEIGHT;
}`
But position: absolute is an even worse solution. In Helix Ultimate 1.1.2, you were on the right track. You just used not quite accurate code to solve the problem. Check this code:
`#sp-header.header-sticky + section {
	padding-top: HEADER_HEIGHT;
}`

**Comment by mdamjadrana** [comment]
This problem already solved.
