### ISSUE TITLE
Two Offcanvas: Left Menu / Right Menu settings

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#81]
Hi guys, 
PHP 7.3.19 + Joomla 3.9.19 + Helix Ultimate 2.0 alpha, right now we have:
- Navigation > Menu Type Off-canvas > Off-canvas Position: Left / **OR** / Right

Instead of it, Please, Do you have on the stable roadmap a simple improvment left/right Offcanvas Menus option ? Like:
- Navigation > Menu Type Off-canvas > Offcanvas Left Menu: enable / disable
- Navigation > Menu Type Off-canvas > Offcanvas Right Menu: enable / disable
Two different menus, the same code / CSS, may be with an icon type setting...

**Comment by mdamjadrana** [comment]
Sorry, we are don't do custom work. Thanks for your opinion.
