### ISSUE TITLE
Page Transitions feature

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#82]
Hi guys, 
from a mobile / touch world point of view, a Page Transitions feature is a must to sliding into Joomla Menus, Categories, Articles: https://tympanus.net/Development/PageTransitions/
- Here [the code source example](https://tympanus.net/codrops/2013/05/07/a-collection-of-page-transitions/)
- [How to slide left / right examples](https://stackoverflow.com/questions/24142682/how-do-you-do-slide-in-from-the-left-and-right-web-page-transitions-using-css)
- [Android examples](https://www.mysamplecode.com/2013/02/android-animation-switching-activity.html)

**Comment by mdamjadrana** [comment]
Sorry, we are not doing custom work.
