### ISSUE TITLE
$alert BUG > Fixing solution

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#84]
Hi guys, 
I found an "[b]Alert BUG[/b]" - in the Profile Edite page the class [alert-notice](https://photos.app.goo.gl/yXzwS89yGQVXAAuu6) should be alert-info

**Solution**
...shaper_helixultimate/html/layouts/joomla/system/message.php line 13 CHANGE

$alert = [
	'message' => 'alert-success',
	'error' => 'alert-danger',
	'warning' => 'alert-danger'
];

WITH

$alert = [
	'message' => 'alert-success',
        **'notice' => 'alert-info',**
        'warning' => 'alert-**warning'**,
	'error' => 'alert-danger'
];

**Comment by ahamed** [comment]
Thank you for your information. The issue is fixed.
