### ISSUE TITLE
Layout Builder > Column Options > Module Position: missing - BUG

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#88]
Hi guys, 
all the last 1.1.2 Module Positions has been lost on 2.0 alpha 1

Please, Can you restore them, "in the extended version" discussed [here](https://www.joomshaper.com/forums/how-to-add-more-bottom-module-positions), in the next release?

**Comment by ahamed** [comment]
What do you mean by **lost**? Did they exist in `v1.1.2` but not in `2.0`?

**Comment by joomleb** [comment]
Hi @ahamed 
I'm sorry I expressed myself wrong. I mean that the "promised" / "announced" adding of the +4 module bottom positions are missing, have been forgotten (the reference is to the discussion in the forum).
By just adding on file templateDetails.xml line 56:

<position>bottom5</position>
<position>bottom6</position>
<position>bottom7</position>
<position>bottom8</position>

**Comment by mdamjadrana** [comment]
As many positions as you need, you can add them into templateDetails.xml anytime.  So do that with your needs.
