### ISSUE TITLE
Coming Soon - countdown not resized - BUG

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#89]
Hi guys, 
PHP 7.3.19 + Joomla .9.20 + Helix Ultimate 2.0 alpha 1

frontend Coming Soon page (here on [test page](https://seblod.egulp.net/), here [an image](https://photos.app.goo.gl/dMyHD9WYkc7MTxb97)), the countdown dimension is not resized on mobile view with the result to be unreadable !

**Comment by mdamjadrana** [comment]
Solved
