### ISSUE TITLE
element-invisible class - missing BUG

### ISSUE THREAD

**Issue by joomleb** [JoomShaper/helix-ultimate#94]
Hi guys, 
we applied the Joomla default element-invisible class (display: none) to our Search label ([an example on this Test2 site page](https://test2.egulp.net/customerdashboard?view=customerinvoices))
On Beez3 and Protostrar it is running well hiding the label. While with Helix Ultimate is still showing it. It seems the class is not defined/applied well.
The class "element-invisible" is supported by default in all Joomla default templates as well as in Joomla 4 for backward compatibility purpose. Helix Ultimate template must support it, this class is used across Joomla code base, it is not just for hiding element, it is also for accessibility purpose.

It has been discussed [here](https://github.com/joomla/joomla-cms/issues/15832) on Joomla 4 GitHub channel

I reported this also [on the Forum here](https://www.joomshaper.com/forums/element-invisible-class-missing-bug)

**Comment by mdamjadrana** [comment]
Added that class.
